{ config, pkgs, ... }:
let
  containerDataPath = "/var/lib/mediawiki";

  version = "1.44.0";

  port = 3026;

  extra-apache-conf = pkgs.writeText "extra.conf" ''
    ServerName 127.0.0.1
  '';

  local-settings = pkgs.writeText "LocalSettings.php.template" ''
    <?php
    # This file was automatically generated by the MediaWiki 1.44.0
    # installer. If you make manual changes, please keep track in case you
    # need to recreate them later.
    #
    # See includes/MainConfigSchema.php for all configurable settings
    # and their default values, but don't forget to make changes in _this_
    # file, not there.
    #
    # Further documentation for configuration settings may be found at:
    # https://www.mediawiki.org/wiki/Manual:Configuration_settings

    # Protect against web entry
    if ( !defined( 'MEDIAWIKI' ) ) {
        exit;
    }

    ## Uncomment this to disable output compression
    # $wgDisableOutputCompression = true;

    $wgSitename = "Magik Voodoo Tantra Grimoire";
    $wgMetaNamespace = "Project";

    ## The URL base path to the directory containing the wiki;
    ## defaults for all runtime URL paths are based off of this.
    ## For more information on customizing the URLs
    ## (like /w/index.php/Page_title to /wiki/Page_title) please see:
    ## https://www.mediawiki.org/wiki/Manual:Short_URL
    $wgScriptPath = "";

    ## The protocol and server name to use in fully-qualified URLs
    $wgServer = "https://wiki.${config.homefree.system.domain}";

    ## The URL path to static resources (images, scripts, etc.)
    $wgResourceBasePath = $wgScriptPath;

    ## The URL paths to the logo.  Make sure you change this from the default,
    ## or else you'll overwrite your logo when you upgrade!
    $wgLogos = [
        '1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
        'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
    ];

    ## UPO means: this is also a user preference option

    $wgEnableEmail = true;
    $wgEnableUserEmail = true; # UPO

    $wgEmergencyContact = "";
    $wgPasswordSender = "";

    $wgEnotifUserTalk = false; # UPO
    $wgEnotifWatchlist = false; # UPO
    $wgEmailAuthentication = true;

    ## Database settings
    $wgDBtype = "mysql";
    $wgDBserver = "10.0.0.1";
    $wgDBname = "mediawiki";
    $wgDBuser = "mediawiki";
    $wgDBpassword = '{{MYSQL_PASSWORD}}';

    # MySQL specific settings
    $wgDBprefix = "";
    $wgDBssl = false;

    # MySQL table options to use during installation or update
    $wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

    # Shared database table
    # This has no effect unless $wgSharedDB is also set.
    $wgSharedTables[] = "actor";

    ## Shared memory settings
    $wgMainCacheType = CACHE_ACCEL;
    $wgMemCachedServers = [];

    ## To enable image uploads, make sure the 'images' directory
    ## is writable, then set this to true:
    $wgEnableUploads = false;
    $wgUseImageMagick = true;
    $wgImageMagickConvertCommand = "/usr/bin/convert";

    # InstantCommons allows wiki to use images from https://commons.wikimedia.org
    $wgUseInstantCommons = false;

    # Periodically send a pingback to https://www.mediawiki.org/ with basic data
    # about this MediaWiki instance. The Wikimedia Foundation shares this data
    # with MediaWiki developers to help guide future development efforts.
    $wgPingback = true;

    # Site language code, should be one of the list in ./includes/languages/data/Names.php
    $wgLanguageCode = "en";

    # Time zone
    $wgLocaltimezone = "UTC";

    ## Set $wgCacheDirectory to a writable directory on the web server
    ## to make your wiki go slightly faster. The directory should not
    ## be publicly accessible from the web.
    #$wgCacheDirectory = "$IP/cache";

    $wgSecretKey = "{{WG_SECRET_KEY}}";

    # Changing this will log out all existing sessions.
    $wgAuthenticationTokenVersion = "1";

    # Site upgrade key. Must be set to a string (default provided) to turn on the
    # web installer while LocalSettings.php is in place
    $wgUpgradeKey = "377f1af203cdd10b";

    ## For attaching licensing metadata to pages, and displaying an
    ## appropriate copyright notice / icon. GNU Free Documentation
    ## License and Creative Commons licenses are supported so far.
    $wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
    $wgRightsUrl = "";
    $wgRightsText = "";
    $wgRightsIcon = "";

    # Path to the GNU diff3 utility. Used for conflict resolution.
    $wgDiff3 = "/usr/bin/diff3";

    ## Default skin: you can change the default skin. Use the internal symbolic
    ## names, e.g. 'vector' or 'monobook':
    $wgDefaultSkin = "monobook";

    # Enabled skins.
    # The following skins were automatically enabled:
    wfLoadSkin( 'MinervaNeue' );
    wfLoadSkin( 'MonoBook' );
    wfLoadSkin( 'Timeless' );
    wfLoadSkin( 'Vector' );


    # End of automatically generated settings.
    # Add more configuration options below.
  '';

  preStart = ''
    mkdir -p ${containerDataPath}/cache
    mkdir -p ${containerDataPath}/html/images
    mkdir -p ${containerDataPath}/html/images

    MYSQL_PASSWORD_RAW=$(cat ${config.homefree.services.mediawiki.secrets.mysql-password})
    # Escape single quotes
    MYSQL_PASSWORD="''${MYSQL_PASSWORD_RAW//\'/\\\'}"
    WG_SECRET_KEY=$(cat ${config.homefree.services.mediawiki.secrets.wgSecretKey})

    ## @TODO: reduce privileges here. mediawiki shouldn't be admin
    ${pkgs.mariadb}/bin/mysql -e "CREATE USER IF NOT EXISTS 'mediawiki'@'localhost'"
    ${pkgs.mariadb}/bin/mysql -e "ALTER USER 'mediawiki'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'";
    ${pkgs.mariadb}/bin/mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mediawiki'@'localhost'"
    ${pkgs.mariadb}/bin/mysql -e "CREATE USER IF NOT EXISTS 'mediawiki'@'%'"
    ${pkgs.mariadb}/bin/mysql -e "ALTER USER 'mediawiki'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'"
    ${pkgs.mariadb}/bin/mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mediawiki'@'%'"

    ${pkgs.gnused}/bin/sed -e "s/{{MYSQL_PASSWORD}}/$MYSQL_PASSWORD/g" \
      -e "s/{{WG_SECRET_KEY}}/$WG_SECRET_KEY/g" \
      ${local-settings} > ${containerDataPath}/LocalSettings.php
  '';
in
{

  services.mysql = {
    ensureDatabases = [
      "mediawiki"
    ];

    ensureUsers = [
      {
        name = "mediawiki";
        ensurePermissions = {
          "mediawiki.*" = "ALL PRIVILEGES";
        };
      }
    ];
  };

  virtualisation.oci-containers.containers = if config.homefree.services.mediawiki.enable == true then {
    mediawiki = {
      image = "mediawiki:${version}";

      autoStart = true;

      extraOptions = [
        # "--pull=always"
        "--add-host=host.docker.internal:host-gateway"
      ];

      ports = [
        "0.0.0.0:${toString port}:80"
      ];

      volumes = [
        "/etc/localtime:/etc/localtime:ro"
        "${containerDataPath}/cache:/var/cache"
        "${containerDataPath}/LocalSettings.php:/var/www/html/LocalSettings.php"
        "${containerDataPath}/html/images:/var/www/html/images"
        "${extra-apache-conf}:/etc/apache2/conf-enabled/extra.conf"
      ];

      ## @TODO: this shouldn't need to be exposed to user config
      environmentFiles = [
        config.homefree.services.mediawiki.secrets.env
      ];

      environment = {
        TZ = config.homefree.system.timeZone;
        MEDIAWIKI_SITE_SERVER = "https://wiki.${config.homefree.system.domain}";
        ## Move to service config
        MEDIAWIKI_SITE_NAME = "Magik Voodoo Tantra Grimoire";
        # MEDIAWIKI_UPDATE = true;
        MEDIAWIKI_DB_TYPE = "mysql";
        MEDIAWIKI_DB_HOST = "10.0.0.1";
        MEDIAWIKI_DB_USER = "mediawiki";
        MEDIAWIKI_DB_NAME = "mediawiki";
        ## In secrets file
        # MEDIAWIKI_ADMIN_PASS = "admin123";
        # MEDIAWIKI_DB_PASSWORD = "admin123";
      };
    };
  } else {};

  systemd.services.podman-mediawiki = {
    after = [ "dns-ready.service" ];
    requires = [ "dns-ready.service" ];
    partOf =  [ "nftables.service" ];
    serviceConfig = {
      ExecStartPre = [ "!${pkgs.writeShellScript "mediawiki-prestart" preStart}" ];
    };
  };

  homefree.service-config = if config.homefree.services.mediawiki.enable == true then [
    {
      label = "mediawiki";
      name = "MediaWiki";
      project-name = "MediaWiki";
      systemd-service-names = [
        "podman-mediawiki"
        "mysql"
      ];
      reverse-proxy = {
        enable = true;
        subdomains = [ "wiki" "mediawiki" ];
        http-domains = [ "homefree.lan" config.homefree.system.localDomain ];
        https-domains = [ config.homefree.system.domain ];
        host = "10.0.0.1";
        port = port;
        public = config.homefree.services.mediawiki.public;
      };
      backup = {
        paths = [
          containerDataPath
        ];
        mysql-databases = [
          "mediawiki"
        ];
      };
    }
  ] else [];
}

