{ config, lib, pkgs, ... }:
let
  ## Update extension versions below when this is updated
  version = "1.45.3";

  databases = lib.map (site: "mediawiki_${site.subdomain}") config.homefree.service-options.mediawiki.sites;

  ## @TODO: Need to manage these ports to avoid conflicts
  initialPort = 7036;

  extra-apache-conf = pkgs.writeText "extra.conf" ''
    ServerName 127.0.0.1
  '';

  resize-logo = image: width: height: if image != null then (pkgs.runCommand "resize-image" {
    src = image;
    buildInputs = [ pkgs.imagemagick ];
  } ''
    convert "$src" -resize '${toString width}x${toString height}>' $out
  '') else null;

  create-favicon = image: if image != null then (pkgs.runCommand "create-favicon" {
    src = image;
    buildInputs = [ pkgs.imagemagick ];
  } ''
    convert "$src" -define icon:auto-resize=16,32,48,64,128,256 $out
  '') else null;

  extensions = pkgs.stdenv.mkDerivation {
    name = "mediawiki-extensions";

    srcs = [
      ## MobileFrontend extension no longer needed, but left here
      ## as reference on how to add external extensions
      (pkgs.fetchFromGitHub {
        name = "MobileFrontend";
        owner = "wikimedia";
        repo = "mediawiki-extensions-MobileFrontend";
        ## Latest commit from tag: REL1_44
        rev = "c75c95d9ce76278973bc2a5de7940e91c28b8cb8";
        sha256 = "sha256-kG82JeHvAG//llxEYQozCJrl08tIEU4fcSicHEeuBU4=";
      })
    ];

    sourceRoot = ".";

    installPhase = ''
      mkdir -p $out
      # Copy each source to the output with the proper name
      cp -r MobileFrontend $out/
    '';
  };

  local-settings-base = ''
    <?php
    # This file was automatically generated by the MediaWiki 1.44.0
    # installer. If you make manual changes, please keep track in case you
    # need to recreate them later.
    #
    # See includes/MainConfigSchema.php for all configurable settings
    # and their default values, but don't forget to make changes in _this_
    # file, not there.
    #
    # Further documentation for configuration settings may be found at:
    # https://www.mediawiki.org/wiki/Manual:Configuration_settings

    # Protect against web entry
    if ( !defined( 'MEDIAWIKI' ) ) {
        exit;
    }

    ## Uncomment this to disable output compression
    # $wgDisableOutputCompression = true;

    $wgMetaNamespace = "Project";

    ## The URL base path to the directory containing the wiki;
    ## defaults for all runtime URL paths are based off of this.
    ## For more information on customizing the URLs
    ## (like /w/index.php/Page_title to /wiki/Page_title) please see:
    ## https://www.mediawiki.org/wiki/Manual:Short_URL
    $wgScriptPath = "";

    ## The URL path to static resources (images, scripts, etc.)
    $wgResourceBasePath = $wgScriptPath;

    ## UPO means: this is also a user preference option

    $wgEnableEmail = true;
    $wgEnableUserEmail = true; # UPO

    $wgEmergencyContact = "";
    $wgPasswordSender = "";

    $wgEnotifUserTalk = false; # UPO
    $wgEnotifWatchlist = false; # UPO
    $wgEmailAuthentication = false;

    ## Database settings
    $wgDBtype = "mysql";
    $wgDBserver = "${config.homefree.network.lan-address}";
    $wgDBuser = "mediawiki";
    $wgDBpassword = '{{MYSQL_PASSWORD}}';

    # MySQL specific settings
    $wgDBprefix = "";
    $wgDBssl = false;

    # MySQL table options to use during installation or update
    $wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

    # Shared database table
    # This has no effect unless $wgSharedDB is also set.
    $wgSharedTables[] = "actor";

    ## Shared memory settings
    $wgMainCacheType = CACHE_ACCEL;
    $wgMemCachedServers = [];

    ## To enable image uploads, make sure the 'images' directory
    ## is writable, then set this to true:
    $wgEnableUploads = true;
    $wgUseImageMagick = true;
    $wgImageMagickConvertCommand = "/usr/bin/convert";

    # InstantCommons allows wiki to use images from https://commons.wikimedia.org
    $wgUseInstantCommons = false;

    # Periodically send a pingback to https://www.mediawiki.org/ with basic data
    # about this MediaWiki instance. The Wikimedia Foundation shares this data
    # with MediaWiki developers to help guide future development efforts.
    $wgPingback = false;

    # Site language code, should be one of the list in ./includes/languages/data/Names.php
    $wgLanguageCode = "en";

    # Time zone
    $wgLocaltimezone = "${config.homefree.system.timeZone}";

    ## Set $wgCacheDirectory to a writable directory on the web server
    ## to make your wiki go slightly faster. The directory should not
    ## be publicly accessible from the web.
    #$wgCacheDirectory = "$IP/cache";

    $wgSecretKey = "{{WG_SECRET_KEY}}";

    # Changing this will log out all existing sessions.
    $wgAuthenticationTokenVersion = "1";

    # Site upgrade key. Must be set to a string (default provided) to turn on the
    # web installer while LocalSettings.php is in place
    $wgUpgradeKey = "377f1af203cdd10b";

    ## For attaching licensing metadata to pages, and displaying an
    ## appropriate copyright notice / icon. GNU Free Documentation
    ## License and Creative Commons licenses are supported so far.
    $wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
    $wgRightsUrl = "";
    $wgRightsText = "";
    $wgRightsIcon = "";

    # Path to the GNU diff3 utility. Used for conflict resolution.
    $wgDiff3 = "/usr/bin/diff3";
    $wgFavicon = "{$wgScriptPath}/images/favicon.ico";

    # Enabled skins.
    # The following skins were automatically enabled:
    wfLoadSkin( 'MinervaNeue' );
    wfLoadSkin( 'MonoBook' );
    wfLoadSkin( 'Timeless' );
    wfLoadSkin( 'Vector' );

    ## Default skin: you can change the default skin. Use the internal symbolic
    ## names, e.g. 'vector' or 'monobook':
    $wgDefaultSkin = "monobook";

    # End of automatically generated settings.
    # Add more configuration options below.

    ## Pretty URLs
    $actions = [
        'view',
        'edit',
        'watch',
        'unwatch',
        'delete',
        'revert',
        'rollback',
        'protect',
        'unprotect',
        'markpatrolled',
        'render',
        'submit',
        'history',
        'purge',
        'info',
    ];

    foreach ( $actions as $action ) {
      $wgActionPaths[$action] = "/$action/$1";
    }
    $wgArticlePath = $wgActionPaths['view'];

    ## Extensions included in base distribution

    wfLoadExtension( 'VisualEditor' );
    wfLoadExtension( 'Scribunto' );
    $wgScribuntoDefaultEngine = 'luastandalone';
    wfLoadExtension( 'InputBox' );
    wfLoadExtension( 'CategoryTree' );
    wfLoadExtension( 'Cite' );
    wfLoadExtension( 'MultimediaViewer' );
    wfLoadExtension( 'Math' );
    wfLoadExtension( 'SyntaxHighlight_GeSHi' );
    wfLoadExtension( 'WikiEditor' );
    $wgDefaultUserOptions['usebetatoolbar'] = 1; // user option provided by WikiEditor extension
    wfLoadExtension( 'Poem' );
    wfLoadExtension( 'PageImages' );
    wfLoadExtension( 'PdfHandler' );
    wfLoadExtension( 'ImageMap' );
    wfLoadExtension( 'CodeEditor' );

    ## No longer needed - mobile has first class support
    # wfLoadExtension( 'MobileFrontend' );
    # $wgMFAutodetectMobileView = true;
    # $wgMFDefaultSkinClass = 'SkinMinerva';

    ## Requires missing binary
    # wfLoadExtension( 'DiscussionTools' );
    ## Causes page to fail to load with "security error"
    # wfLoadExtension( 'Echo' );
  '';
in
{
  options.homefree.service-options.mediawiki = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "enable MediaWiki";
    };

    public = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Open to public on WAN port";
    };

    sites = lib.mkOption {
      description = "Wiki site config";
      default = [];
      type = with lib.types; listOf (submodule {
        options = {
          public = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Open to public on WAN port";
          };
          subdomain = lib.mkOption {
            type = lib.types.str;
            default = "wiki";
            description = "Subdomain for wiki (must be unique)";
          };
          name = lib.mkOption {
            type = lib.types.str;
            default = "Wiki";
            description = "Name for site";
          };
          logo-path = lib.mkOption {
            type = lib.types.path;
            description = "Location of MediaWiki logo file";
          };
        };
      });
    };

    secrets = lib.mkOption {
      type = lib.types.attrsOf (lib.types.nullOr lib.types.path);
      default = {};
      description = "Secrets for MediaWiki service";
    };
  };

  config = {
    services.mysql = {
  ensureDatabases = databases;

  ensureUsers = [
    {
      name = "mediawiki";
      ensurePermissions = {
        "mediawiki.*" = "ALL PRIVILEGES";
      };
    }
  ];
};

virtualisation.oci-containers.containers = lib.optionalAttrs config.homefree.service-options.mediawiki.enable
  (lib.listToAttrs
    (lib.imap0 (index: site:
    let
      site-id = "mediawiki_${site.subdomain}";
      containerDataPath = "/var/lib/${site-id}";

      ## @TODO: Break out into function
      logo-raw = site.logo-path;
      logo-basename = if logo-raw != null then (builtins.baseNameOf logo-raw) else null;
      # Split the filename by the dot
      parts = lib.strings.splitString "." logo-basename;
      # Check if there's an extension
      hasExtension = builtins.length parts > 1;
      logo-basename-no-ext = if hasExtension then lib.strings.concatStringsSep "." (lib.lists.take (builtins.length parts - 1) parts) else logo-basename;
      logo-ext = if hasExtension then builtins.elemAt parts (builtins.length parts - 1) else "";

      favicon = create-favicon logo-raw;
      logo-icon = resize-logo logo-raw 100 100;
      logo-1x = resize-logo logo-raw 135 155;
    in
    {
      name = "mediawiki_${site.subdomain}";
      value = {
        image = "mediawiki:${version}";

        autoStart = true;

        extraOptions = [
          # "--pull=always"
          "--add-host=host.docker.internal:host-gateway"
        ];

        ports = [
          "0.0.0.0:${toString (initialPort + index)}:80"
        ];

        volumes = [
          "/etc/localtime:/etc/localtime:ro"
          "${containerDataPath}/cache:/var/cache"
          "${containerDataPath}/LocalSettings.php:/var/www/html/LocalSettings.php"
          "${containerDataPath}/html/images:/var/www/html/images"
          "${extensions}/MobileFrontend:/var/www/html/extensions/MobileFrontend:ro"
          "${extra-apache-conf}:/etc/apache2/conf-enabled/extra.conf"
        ] ++ (if logo-raw != null then [
          "${site.logo-path}:/var/www/html/images/${logo-basename}"
          "${favicon}:/var/www/html/images/favicon.ico"
          "${logo-1x}:/var/www/html/images/${logo-basename-no-ext}-1x.${logo-ext}"
          "${logo-icon}:/var/www/html/images/${logo-basename-no-ext}-icon.${logo-ext}"
        ] else []);

        ## @TODO: this shouldn't need to be exposed to user config
        environmentFiles = lib.optional
          (config.homefree.service-options.mediawiki.secrets.env != null)
          config.homefree.service-options.mediawiki.secrets.env;

        environment = {
          TZ = config.homefree.system.timeZone;
          MEDIAWIKI_SITE_SERVER = "https://${site.subdomain}.${config.homefree.system.domain}";
          ## Move to service config
          MEDIAWIKI_SITE_NAME = site.name;
          # MEDIAWIKI_UPDATE = true;
          MEDIAWIKI_DB_TYPE = "mysql";
          MEDIAWIKI_DB_HOST = "${config.homefree.network.lan-address}";
          MEDIAWIKI_DB_USER = "mediawiki";
          MEDIAWIKI_DB_NAME = site-id;
          ## In secrets file
          # MEDIAWIKI_ADMIN_PASS = "admin123";
          # MEDIAWIKI_DB_PASSWORD = "admin123";
        };
      };
    }) config.homefree.service-options.mediawiki.sites)
  );

  systemd.services = lib.optionalAttrs config.homefree.service-options.mediawiki.enable
  (lib.listToAttrs (
    lib.map (site:
    let
      site-id = "mediawiki_${site.subdomain}";
      containerDataPath = "/var/lib/${site-id}";

      ## @TODO: Break out into function
      logo-raw = site.logo-path;
      logo-basename = if logo-raw != null then (builtins.baseNameOf logo-raw) else null;
      # Split the filename by the dot
      parts = lib.strings.splitString "." logo-basename;
      # Check if there's an extension
      hasExtension = builtins.length parts > 1;
      logo-basename-no-ext = if hasExtension then lib.strings.concatStringsSep "." (lib.lists.take (builtins.length parts - 1) parts) else logo-basename;
      logo-ext = if hasExtension then builtins.elemAt parts (builtins.length parts - 1) else "";

      local-settings = pkgs.writeText "LocalSettings-${site-id}.php.template" (local-settings-base
      + ''
        ## The protocol and server name to use in fully-qualified URLs
        $wgServer = "https://${site.subdomain}.${config.homefree.system.domain}";
        $wgSitename = "${site.name}";
        $wgDBname = "${site-id}";
      ''
      + (if site.readonly || site.disable-user-editing || site.disable-anonymous-editing then ''
        $wgGroupPermissions['*']['edit'] = false;
      '' else "")
      + (if site.readonly || site.disable-user-editing  then ''
        $wgGroupPermissions['user']['edit'] = false;
      '' else "")
      + (if site.readonly then ''
        $wgGroupPermissions['sysop']['edit'] = false;
      '' else "")
      + (if site.disable-anonymous-viewing then ''
        $wgGroupPermissions['*']['read'] = false;
      '' else "")
      + (if site.disable-user-registration then ''
        $wgGroupPermissions['*']['createaccount'] = false;
        $wgGroupPermissions['sysop']['createaccount'] = true;
      '' else "")
      + (if logo-raw == null then ''
        $wgLogos = [
            '1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
            'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
        ];
      '' else ''
        $wgLogos = [
            '1x' => "{$wgScriptPath}/images/${logo-basename-no-ext}-1x.${logo-ext}",
            'icon' => "{$wgScriptPath}/images/${logo-basename-no-ext}-icon.${logo-ext}",
        ];
      '')
      );
      preStart = ''
        ## MySQL setup is not currently site specific, so it is being run
        ## for each site, even though it only needs to currently be run once.
        ## Leaving it here though as each DB for each site should have its own perms.
        MYSQL_PASSWORD_RAW=$(cat ${config.homefree.service-options.mediawiki.secrets.mysql-password})
        # Escape single quotes
        MYSQL_PASSWORD="''${MYSQL_PASSWORD_RAW//\'/\\\'}"
        WG_SECRET_KEY=$(cat ${config.homefree.service-options.mediawiki.secrets.wgSecretKey})

        ## @TODO: reduce privileges here. mediawiki shouldn't be admin
        ${pkgs.mariadb}/bin/mysql -e "CREATE USER IF NOT EXISTS 'mediawiki'@'localhost'"
        ${pkgs.mariadb}/bin/mysql -e "ALTER USER 'mediawiki'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD'";
        ${pkgs.mariadb}/bin/mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mediawiki'@'localhost'"
        ${pkgs.mariadb}/bin/mysql -e "CREATE USER IF NOT EXISTS 'mediawiki'@'%'"
        ${pkgs.mariadb}/bin/mysql -e "ALTER USER 'mediawiki'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'"
        ${pkgs.mariadb}/bin/mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mediawiki'@'%'"

        ## Site specific
        mkdir -p ${containerDataPath}/cache
        mkdir -p ${containerDataPath}/html/images
        chgrp -R www-data ${containerDataPath}
        chmod -R 770 ${containerDataPath}

        ${pkgs.gnused}/bin/sed -e "s/{{MYSQL_PASSWORD}}/$MYSQL_PASSWORD/g" \
          -e "s/{{WG_SECRET_KEY}}/$WG_SECRET_KEY/g" \
          ${local-settings} > ${containerDataPath}/LocalSettings.php
      '';
      postStart = ''
        # Wait for container to be ready
        sleep 10

        # Check if database needs initialization (no tables exist)
        TABLE_COUNT=$(${pkgs.mariadb}/bin/mysql -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '${site-id}'")

        if [ "$TABLE_COUNT" -eq 0 ]; then
          echo "Initializing MediaWiki database for ${site-id}..."
          ${pkgs.podman}/bin/podman exec ${site-id} php /var/www/html/maintenance/run.php installPreConfigured
        else
          echo "MediaWiki database ${site-id} already initialized ($TABLE_COUNT tables)"
        fi
      '';
    in
    {
      name = "podman-${site-id}";
      value = {
        after = [ "dns-ready.service" ];
        requires = [ "dns-ready.service" ];
        partOf =  [ "nftables.service" ];
        serviceConfig = {
          ExecStartPre = [ "!${pkgs.writeShellScript "${site-id}-prestart" preStart}" ];
          ExecStartPost = [ "!${pkgs.writeShellScript "${site-id}-poststart" postStart}" ];
        };
      };
    }) config.homefree.service-options.mediawiki.sites)
  );

  homefree.service-config = lib.optionals config.homefree.service-options.mediawiki.enable
  (lib.imap0 (index: site:
  let
    site-id = "mediawiki_${site.subdomain}";
    containerDataPath = "/var/lib/${site-id}";
  in
  {
    label = site-id;
    name = "MediaWiki - ${site.name}";
    project-name = "MediaWiki";
    systemd-service-names = [
      "podman-${site-id}"
      "mysql"
    ];
    reverse-proxy = {
      enable = config.homefree.service-options.mediawiki.enable;
      subdomains = [ site.subdomain ];
      http-domains = [ "homefree.lan" config.homefree.system.localDomain ];
      https-domains = [ config.homefree.system.domain ];
      host = config.homefree.network.lan-address;
      port = initialPort + index;
      public = site.public;
    };
    backup = {
      paths = [
        containerDataPath
      ];
      mysql-databases = [
        site-id
      ];
    };
  }) config.homefree.service-options.mediawiki.sites);
  };
}

