{ config, lib, pkgs, ... }:

## Default username: <adminUsername> (no orgdomain suffix -- the
## zitadel-provision oneshot disables `userLoginMustBeDomain` on first run)
## Default password: pulled from /var/lib/homefree-secrets/zitadel/admin-password
## (written by the web installer in the same step that hashes the OS
## password for /etc/shadow).
##
## This module bundles Zitadel together with its companion oauth2-proxy.
## The two are always deployed as a pair -- oauth2-proxy is the OIDC bridge
## that lets services that don't speak OIDC natively authenticate via
## Zitadel. Splitting them across files made cross-coupling (shared
## secrets, deploy-together gating) awkward, so they live together here.
##
## Three classes of secrets live under /var/lib/homefree-secrets/zitadel/:
##   - masterkey, oauth2-cookie-secret: auto-generated at first boot
##     by zitadel-prepare-secrets.service (no user input required)
##   - admin-password: written by the web installer
##   - oidc-client-id, oidc-client-secret: written by
##     zitadel-provision.service after Zitadel is healthy (these are
##     for the homefree-oauth2proxy OIDC app -- same naming convention
##     as every other service's secrets dir)

let
  userOptions = {
    enable = lib.mkOption {
      type = lib.types.bool;
      ## Zitadel is the SSO backbone; enabled by default.
      default = true;
      description = "enable Zitadel auth service";
    };

    public = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Open to public on WAN port";
    };
  };

  zitadelVersion = "v4.15.1";
  zitadelDataPath = "/var/lib/zitadel";
  zitadelPort = 3241;

  ## v4 split the login UI into a separate Next.js container
  ## (ghcr.io/zitadel/zitadel-login) -- the API container alone
  ## responds to /ui/v2/login/* with `{"code":5, "Not Found"}`.
  ## We deploy the login container alongside the API and route
  ## /ui/v2/login/* to it via Caddy.
  zitadelLoginPort = 3242;
  ## Shared dir between API + login containers. The API writes the
  ## login-client PAT here on FirstInstance setup
  ## (ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH); the login container
  ## reads it from the same path (ZITADEL_SERVICE_USER_TOKEN_FILE).
  ## On the host, files are owned by UID 1000 (matching both
  ## containers' "zitadel" user).
  zitadelBootstrapPath = "${zitadelDataPath}/bootstrap";
  loginClientPatFile = "${zitadelBootstrapPath}/login-client.pat";

  oauth2ProxyVersion = "v7.12.0";
  ## oauth2-proxy runs blue/green (lib/blue-green.nix) for zero-downtime
  ## rebuilds -- two colour containers on two ports. blue keeps the
  ## historical :4180; green is :4181.
  oauth2ProxyColours = { blue = 4180; green = 4181; };
  oauth2ProxyEnvFile = "/var/lib/oauth2-proxy/env";

  # Per-secret files for everything Zitadel + its bundled oauth2-proxy need.
  # See header comment for which entries are auto-generated vs installer-
  # written vs provision-script-written.
  zitadelSecretsDir = "/var/lib/homefree-secrets/zitadel";

  # Anchors auto-generated secrets into the encrypted /etc/nixos/secrets
  # store so they survive a restore -- see lib/secrets-anchor.nix.
  anchor = import ../../lib/secrets-anchor.nix { inherit lib pkgs; };

  # oauth2-proxy reads its three required secrets from per-secret files
  # under /var/lib/homefree-secrets/zitadel/. We synthesise an env file
  # at runtime rather than baking secrets into the unit.
  #
  # Naming: cookie secret keeps its `oauth2-` prefix because it's an
  # oauth2-proxy-specific artifact (auto-generated by
  # zitadel-prepare-secrets). The client-id / client-secret use the
  # same `oidc-client-*` naming as every other service's secrets,
  # since they ARE per-service OIDC creds (the Zitadel app is just
  # called "homefree-oauth2proxy") and the provision script writes
  # them with that uniform convention.
  oauth2ProxyPreStart = ''
    mkdir -p /var/lib/oauth2-proxy
    {
      if [ -s "${zitadelSecretsDir}/oauth2-cookie-secret" ]; then
        echo "OAUTH2_PROXY_COOKIE_SECRET=$(cat "${zitadelSecretsDir}/oauth2-cookie-secret")"
      fi
      if [ -s "${zitadelSecretsDir}/oidc-client-id" ]; then
        echo "OAUTH2_PROXY_CLIENT_ID=$(cat "${zitadelSecretsDir}/oidc-client-id")"
      fi
      if [ -s "${zitadelSecretsDir}/oidc-client-secret" ]; then
        echo "OAUTH2_PROXY_CLIENT_SECRET=$(cat "${zitadelSecretsDir}/oidc-client-secret")"
      fi
    } > "${oauth2ProxyEnvFile}"
    chmod 600 "${oauth2ProxyEnvFile}"
  '';

  ## ExecStartPre: refuse to start until the three OIDC secrets exist
  ## (oauth2-proxy crash-loops without them). Runs for BOTH colours.
  oauth2ProxySecretsCheck = pkgs.writeShellScript "oauth2-proxy-secrets-check" ''
    for f in oauth2-cookie-secret oidc-client-id oidc-client-secret; do
      if [ ! -s "${zitadelSecretsDir}/$f" ]; then
        echo "oauth2-proxy: ${zitadelSecretsDir}/$f missing or empty — refusing to start" >&2
        exit 1
      fi
    done
  '';

  ## Readiness gate consulted by the blue/green flip + supervisor (NOT an
  ## ExecStartPre — a false result means "defer the start", not "fail the
  ## unit"). It is strictly broader than the secrets check: the secrets
  ## existing on disk does NOT mean Zitadel is SERVING. On a steady-state
  ## rebuild Zitadel's container restarts; until it finishes initialising,
  ## Caddy answers its https://sso.<domain> vhost with a 502. oauth2-proxy
  ## does OIDC discovery at startup and EXITS 1 on that 502 — five fast
  ## exits trip the colour's Restart=on-failure start-limit (burst 5 /
  ## 1 min) and leave a FAILED unit that makes the whole rebuild exit
  ## non-zero. The secrets-only gate didn't catch this because on any box
  ## past first-install the secrets are already present, so it passed
  ## instantly and let the colour fast-fail against a not-yet-ready
  ## Zitadel. So additionally probe the exact self-call oauth2-proxy makes
  ## — loopback-pinned (--network=host + --add-host sso:127.0.0.1, see
  ## mkOauth2ProxyContainer), skip-verify against Caddy's internal CA —
  ## and refuse to start the colour until discovery returns 200. The flip
  ## and supervisor then defer cleanly (current colour keeps serving) and
  ## bring the colour up the instant Zitadel is ready.
  oauth2ProxyReadinessGate = pkgs.writeShellScript "oauth2-proxy-readiness" ''
    ${oauth2ProxySecretsCheck} || exit 1
    ${pkgs.curl}/bin/curl -fsk --max-time 3 -o /dev/null \
      --resolve sso.${config.homefree.system.domain}:443:127.0.0.1 \
      https://sso.${config.homefree.system.domain}/.well-known/openid-configuration
  '';

  ## Factory for an oauth2-proxy colour container. Differs between
  ## colours ONLY by port (`ports` mapping + OAUTH2_PROXY_HTTP_ADDRESS)
  ## -- see the INVARIANT in lib/blue-green.nix. autoStart=false: only
  ## the active colour is started, by oauth2-proxy-active.service.
  ## The shared env file holds only the three (port-independent)
  ## secrets, so both colours share it safely.
  mkOauth2ProxyContainer = colour: port: {
    image = "oauth2-proxy/oauth2-proxy:${oauth2ProxyVersion}";
    autoStart = false;
    ## OIDC discovery + token redemption are a self-call. The issuer
    ## (OAUTH2_PROXY_OIDC_ISSUER_URL below) must stay the public FQDN
    ## https://sso.<domain> so the token `iss` and the browser login URL
    ## match — but that name must resolve to THIS box, not out to public
    ## DNS. Without pinning it, the box's resolver recurses to the public
    ## A/AAAA (the apex, via the `*` CNAME), so oauth2-proxy dials whatever
    ## the current/stale public IP points at: a WAN-IP change, DDNS lag, or
    ## a stale resolver-cache entry then breaks startup ("tls: internal
    ## error" / connection failure) and, with it, the blue/green flip.
    ## Pin it to loopback instead: --network=host means 127.0.0.1 is the
    ## box's own Caddy, which serves sso.<domain> with a valid cert. The
    ## self-call is now independent of public DNS entirely. Browser-facing
    ## redirects are unaffected — those resolve on the user's client.
    extraOptions = [
      "--network=host"
      "--add-host=sso.${config.homefree.system.domain}:127.0.0.1"
    ];
    ports = [ "0.0.0.0:${toString port}:${toString port}" ];
    volumes = [ "/etc/localtime:/etc/localtime:ro" ];
    environment = {
      TZ = config.homefree.system.timeZone;
      OAUTH2_PROXY_PROVIDER = "oidc";
      OAUTH2_PROXY_OIDC_ISSUER_URL = "https://sso.${config.homefree.system.domain}";
      OAUTH2_PROXY_REDIRECT_URL = "https://auth.${config.homefree.system.domain}/oauth2/callback";
      OAUTH2_PROXY_EMAIL_DOMAINS = "*";
      OAUTH2_PROXY_COOKIE_DOMAINS = ".${config.homefree.system.domain}";
      OAUTH2_PROXY_WHITELIST_DOMAINS = ".${config.homefree.system.domain}";
      ## Per-colour listen port -- the one value that differs.
      OAUTH2_PROXY_HTTP_ADDRESS = "0.0.0.0:${toString port}";
      OAUTH2_PROXY_REVERSE_PROXY = "true";
      OAUTH2_PROXY_COOKIE_SECURE = "true";
      OAUTH2_PROXY_COOKIE_HTTPONLY = "true";
      OAUTH2_PROXY_SCOPE = "openid email profile urn:zitadel:iam:org:project:roles";
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM = "urn:zitadel:iam:org:project:roles";
      ## See the long note in the prior single-container definition:
      ## admin-only gating happens in the FastAPI middleware, not here,
      ## because Zitadel's role claim is an object oauth2-proxy v7's
      ## group parser can't key. # OAUTH2_PROXY_ALLOWED_GROUPS = ...
      ##
      ## Caddy serves sso.<domain> with its internal CA; skip-verify is
      ## safe over the local bridge (we're talking to ourselves).
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY = "true";
      OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION = "false";
      OAUTH2_PROXY_PASS_USER_HEADERS = "true";
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER = "true";
      ## SET_XAUTHREQUEST emits X-Auth-Request-* on /oauth2/auth -- what
      ## Caddy's forward_auth copies. Without it the backend rejects
      ## with "missing X-Auth-Request-User".
      OAUTH2_PROXY_SET_XAUTHREQUEST = "true";
      OAUTH2_PROXY_OIDC_EMAIL_CLAIM = "email";
      ## preferred_username (not the numeric `sub`) so the value
      ## matches the OS-side admin username the middleware compares.
      OAUTH2_PROXY_USER_ID_CLAIM = "preferred_username";
    };
    # Env file synthesised by the prestart from the SOPS-managed
    # secrets -- colour-independent, both colours share it.
    environmentFiles = [ oauth2ProxyEnvFile ];
  };

  ## Blue/green machinery for oauth2-proxy. Pure call -- only the
  ## merged `oauth2ProxyBg.config` is gated on zitadelEnabled below.
  oauth2ProxyBg = (import ../../lib/blue-green.nix { inherit lib pkgs; }) {
    name = "oauth2-proxy";
    stateDir = "/var/lib/oauth2-proxy";
    colours = oauth2ProxyColours;
    workload = {
      kind = "oci-container";
      mkContainer = mkOauth2ProxyContainer;
      ## Merged into each generated podman-oauth2-proxy-<colour>.service.
      ## NOTE: lib/blue-green.nix forces `restartIfChanged = false` AND
      ## `stopIfChanged = false` on every colour unit -- the flip owns
      ## the full lifecycle, so we do NOT set them here.
      extraUnitConfig = colour: {
        after = [ "dns-ready.service" "zitadel-prepare-secrets.service" ];
        requires = [ "zitadel-prepare-secrets.service" ];
        wants = [ "dns-ready.service" ];
        serviceConfig.ExecStartPre = [
          "!${oauth2ProxySecretsCheck}"
          "!${pkgs.writeShellScript "oauth2-proxy-prestart" oauth2ProxyPreStart}"
        ];
      };
    };
    healthCheck = { kind = "http"; path = "/ping"; };
    ## A container definition change shows up as a new generated
    ## unit-file hash for the canonical (blue) colour.
    closure = { kind = "unit-file"; colour = "blue"; };
    caddySnippets = [
      {
        snippetName = "oauth2_proxy_forward_auth";
        body = ''
          	forward_auth @sso_gate http://${config.homefree.network.lan-address}:__PORT__ {
          		uri /oauth2/auth
          		copy_headers X-Auth-Request-User X-Auth-Request-Preferred-Username X-Auth-Request-Email X-Auth-Request-Access-Token X-Auth-Request-Groups
          		@bad_status status 401
          		handle_response @bad_status {
          			redir https://auth.${config.homefree.system.domain}/oauth2/start?rd={scheme}://{host}{uri} 302
          		}
          	}'';
      }
      {
        snippetName = "oauth2_proxy_reverse_proxy";
        body = ''	reverse_proxy http://${config.homefree.network.lan-address}:__PORT__'';
      }
    ];
    migrateFrom = "podman-oauth2-proxy.service";
    migrateRollback = "leave-down";
    failureMarker = "oauth2-proxy-flip-failed.json";
    ## Readiness gate (see lib/blue-green.nix). oauth2-proxy's OIDC
    ## secrets (client-id, client-secret, cookie secret) are written by
    ## Zitadel's post-activation provisioning job, so on a FIRST install
    ## they do not exist when this flip runs during activation. Without
    ## this gate the flip + supervisor start blue, its ExecStartPre
    ## secrets check fails, and the supervisor crash-loops it into
    ## `start-limit-hit` -- a failed unit that makes the finishing rebuild
    ## exit non-zero and leaves the box stuck in finish-setup. The gate
    ## defers bring-up to the supervisor, which starts blue the moment the
    ## prerequisites land. Broader than the colour's ExecStartPre secrets
    ## check: it ALSO probes that Zitadel is actually serving OIDC
    ## discovery (not merely that the secrets exist), so a colour is never
    ## started against a restarting Zitadel — which 502s discovery and
    ## crash-loops the colour into start-limit-hit. See the gate's own
    ## definition above for the full rationale.
    readinessGate = "${oauth2ProxyReadinessGate}";
    ## Order this flip after admin-api's snippet writer, so admin-api's
    ## file-scope Caddy `import` target exists before this flip reloads
    ## Caddy. The name is the static `${name}-bg-snippet` of
    ## services/admin-web/default.nix's admin-api blue/green instance.
    snippetActivationDeps = [ "admin-api-bg-snippet" ];
  };

  zitadelEnabled = config.homefree.service-options.zitadel.enable;

  # Env file synthesised at preStart so the masterkey + admin password
  # are loaded from on-disk per-secret files (auto-generated for the
  # masterkey, installer-written for the admin password).
  zitadelEnvFile = "/var/lib/zitadel/env";
  ## The Zitadel container runs as user "zitadel" (UID/GID 1000 in the
  ## upstream image). With rootful podman, that maps directly to host
  ## UID 1000, so the data directory needs to be owned/writable by
  ## that UID for the container to write /data/pat-bootstrap (and any
  ## other runtime files). Without this the FirstInstance migration
  ## fails with "open /data/pat-bootstrap: permission denied" -- but
  ## not before partially populating the eventstore, which then
  ## permanently breaks subsequent retries with
  ## Errors.Instance.Domain.AlreadyExists collisions (the failed
  ## migration's partial state never rolls back).
  zitadelContainerUid = 1000;
  zitadelContainerGid = 1000;
  zitadelPreStart = ''
    set -eu
    mkdir -p ${zitadelDataPath}
    chown ${toString zitadelContainerUid}:${toString zitadelContainerGid} ${zitadelDataPath}
    chmod 700 ${zitadelDataPath}

    ## Bootstrap dir shared with the zitadel-login container. Holds the
    ## login-client PAT that the API writes on FirstInstance and that
    ## the login container reads at startup.
    mkdir -p ${zitadelBootstrapPath}
    chown ${toString zitadelContainerUid}:${toString zitadelContainerGid} ${zitadelBootstrapPath}
    chmod 700 ${zitadelBootstrapPath}

    ## db-user-password is anchored HERE (not in
    ## zitadel-prepare-secrets) because NixOS's switch-to-configuration
    ## does NOT reliably re-run oneshot+RemainAfterExit units when their
    ## ExecStart hash or X-Restart-Triggers change -- the unit is
    ## already "active (exited)" from a prior boot and stays that way.
    ## Container ExecStartPre, by contrast, re-runs every time the
    ## container restarts, and rebuilds always restart the container
    ## when its content changes. Same pattern snipe-it, nextcloud,
    ## linkwarden, screeenly use. The anchor helper is idempotent so
    ## putting the call here doesn't break anything; it just makes the
    ## materialisation reliable on every existing instance.
    mkdir -p ${zitadelSecretsDir}
    ${anchor.preamble}
    ${anchor.anchorSecret {
      service = "zitadel";
      key = "db-user-password";
      dir = zitadelSecretsDir;
      generate = "${pkgs.openssl}/bin/openssl rand -base64 32 | tr -d '/+=' | head -c 32";
    }}

    install -m 600 /dev/null ${zitadelEnvFile}
    {
      if [ -s "${zitadelSecretsDir}/masterkey" ]; then
        echo "ZITADEL_MASTERKEY=$(cat ${zitadelSecretsDir}/masterkey)"
      fi
      if [ -s "${zitadelSecretsDir}/admin-password" ]; then
        echo "ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=$(cat ${zitadelSecretsDir}/admin-password)"
      fi
      ## DB password for the "zitadel" Postgres role on the host
      ## cluster. Today the host pg_hba uses trust auth on the podman
      ## bridge so the value is sent-but-ignored; Phase 2's pg_hba
      ## swap makes it live.
      echo "ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=$(cat ${zitadelSecretsDir}/db-user-password)"
      ## Cluster superuser password -- anchored + rotated by
      ## services/postgres's postgres-anchor-superuser-password
      ## oneshot. Used by Zitadel's init container to CREATE ROLE
      ## zitadel / CREATE DATABASE zitadel. The systemd unit below
      ## orders podman-zitadel after the oneshot so this file is
      ## guaranteed to exist by the time we read it.
      if [ -s /var/lib/homefree-secrets/postgres/superuser-password ]; then
        echo "ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=$(cat /var/lib/homefree-secrets/postgres/superuser-password)"
      fi
    } > ${zitadelEnvFile}
    ## env file is read by podman from the host (not the container),
    ## so it stays root:root mode 600 -- only the directory itself
    ## needs to be writable by the container.

    ## Idempotent rotation of the "zitadel" Postgres role's password.
    ## On a fresh install the role doesn't exist yet (the Zitadel init
    ## container creates it on first boot via the ADMIN credentials),
    ## so the ALTER is guarded behind an existence check -- first-boot
    ## skips, subsequent boots rotate from whatever the historical
    ## literal was to the current anchored value, and steady-state
    ## boots set it to itself.
    ZITADEL_DB_PASSWORD=$(cat ${zitadelSecretsDir}/db-user-password)
    ${pkgs.postgresql}/bin/psql -h /run/postgresql -U postgres <<PGEOF || true
      DO \$do\$
      BEGIN
        IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'zitadel') THEN
          EXECUTE format('ALTER ROLE %I WITH PASSWORD %L', 'zitadel', '$ZITADEL_DB_PASSWORD');
        END IF;
      END
      \$do\$;
PGEOF
  '';

  ## Body of zitadel-prepare-secrets.service. Extracted to a let-binding
  ## so it can be referenced by both `script` and `restartTriggers`
  ## below -- see the long comment on `restartTriggers` for why.
  zitadelPrepareSecretsScript = ''
    ${anchor.preamble}

    ## masterkey -- must be exactly 32 bytes. `openssl rand -hex 16`
    ## is 32 ASCII chars -> 32 bytes, and avoids the base64 padding
    ## `=` issue that breaks ZITADEL_MASTERKEY parsing in some shells.
    ${anchor.anchorSecret {
      service = "zitadel";
      key = "masterkey";
      dir = zitadelSecretsDir;
      generate = "${pkgs.openssl}/bin/openssl rand -hex 16";
    }}

    ${anchor.anchorSecret {
      service = "zitadel";
      key = "oauth2-cookie-secret";
      dir = zitadelSecretsDir;
      generate = "${pkgs.openssl}/bin/openssl rand -base64 32 | head -c 32";
    }}

    ## NOTE: db-user-password is intentionally NOT anchored here. It
    ## lives in zitadelPreStart (podman-zitadel's ExecStartPre)
    ## because oneshot+RemainAfterExit units don't re-run reliably on
    ## switch-to-configuration even with X-Restart-Triggers set,
    ## leaving the secret missing on existing instances. The container
    ## prestart pattern is the same one used by snipe-it, nextcloud,
    ## linkwarden, screeenly and runs every time the container restarts.

    ## admin-password -- the initial Zitadel admin password. In the
    ## normal install flow it's written by the web installer
    ## (web-platform/backend/services/install.py:1549) to match the OS
    ## admin user's password, so SSO + shell credentials are unified
    ## from the very first boot. The PAM bridge
    ## (apps/zitadel/pam-bridge.nix) keeps them in sync going forward
    ## by POSTing every later `passwd` change to Zitadel's API.
    ##
    ## End users never log into Zitadel directly -- orchestration is
    ## handled by install.py and the HomeFree admin-api backend.
    ##
    ## This auto-generate path is a SAFETY NET for the case where
    ## install.py never ran (skipped install, manual rebuild, file
    ## wiped). Without it Zitadel would fall back to its compiled-in
    ## default password, which is weak and well-known. Generating a
    ## strong random value here keeps the bootstrap secure even when
    ## the normal flow was bypassed; recovery is to set the OS
    ## password (e.g., via the installer or `passwd`), which the
    ## PAM bridge then propagates into Zitadel.
    ##
    ## adoptExisting=false: the PAM bridge updates Zitadel via its
    ## Management API but does NOT rewrite this file, so the on-disk
    ## value goes stale the moment the OS admin first changes their
    ## password. Anchoring the file's value would persist a
    ## possibly-stale credential into the encrypted store. We anchor
    ## only on fresh generation -- branch (3) of secrets-anchor.nix --
    ## and let install.py's write be the source of truth for the
    ## happy path. Base64-of-24-bytes minus /+= is mixed-case
    ## alphanumeric, satisfying Zitadel's default policy.
    ${anchor.anchorSecret {
      service = "zitadel";
      key = "admin-password";
      dir = zitadelSecretsDir;
      adoptExisting = false;
      generate = "${pkgs.openssl}/bin/openssl rand -base64 24 | tr -d '/+=' | head -c 24";
      onGenerate = ''
        ## Operator-facing journal warning. End users should never
        ## reach this -- install.py writes admin-password as part of
        ## the normal install flow, so a freshly-generated value
        ## here means the install flow was skipped or the file was
        ## wiped. The value is unknown to the OS user, so SSO
        ## still works for them via the PAM bridge as soon as they
        ## run `passwd` (or re-run the installer).
        ##
        ## Tagged with WARNING so it shows up at -p warning in
        ## journalctl.
        logger -t zitadel-prepare-secrets -p warning \
          "Generated a fresh Zitadel admin password as a safety-net (install.py did not stash one). Run \`passwd\` as the OS admin to sync, or re-run the installer. The generated value is at ${zitadelSecretsDir}/admin-password -- only readable by root."
      '';
    }}
  '';

  ## (Historically there was a `deployOauth2Proxy` symbol here that
  ## gated the oauth2-proxy container on the existence of three SOPS
  ## secret files via builtins.pathExists. That gate caused a
  ## double-rebuild UX: build #1 lands the provisioning, build #2 is
  ## needed for Nix to re-eval pathExists and actually deploy
  ## oauth2-proxy. We removed it: oauth2-proxy is now always
  ## rendered when Zitadel is enabled but its ExecStartPre refuses
  ## to launch without the secrets, and zitadel-provision.service
  ## starts it once they land.)
in
{
  ## Zitadel ships as four sibling modules in this directory. The
  ## entrypoint (`default.nix`) imports the other three so a caller
  ## only has to import `apps/zitadel` to pull in the whole stack.
  imports = [
    ./provision.nix
    ./pam-bridge.nix
    ./password-shim.nix
  ];

  options.homefree.services.zitadel = userOptions;
  options.homefree.service-options.zitadel = userOptions // {
    label = lib.mkOption {
      type = lib.types.str;
      default = "zitadel";
      internal = true;
      description = "Service label";
    };

    name = lib.mkOption {
      type = lib.types.str;
      default = "Single Sign-on (SSO)";
      internal = true;
      description = "Service display name";
    };

    project-name = lib.mkOption {
      type = lib.types.str;
      default = "Zitadel";
      internal = true;
      description = "Project name";
    };

    ## Zitadel's secrets (masterkey, admin password, oauth2 cookie
    ## secret, OIDC client_id/secret for the oauth2-proxy app) are
    ## all auto-provisioned: zitadel-prepare-secrets.service generates
    ## the masterkey + cookie secret on first boot; the web installer
    ## sets the admin password; zitadel-provision.service mints the
    ## OAuth2 Proxy OIDC app and writes its client_id/secret. preStart
    ## scripts read the files directly from /var/lib/homefree-secrets/
    ## zitadel/, bypassing the Nix-config layer. No option declarations
    ## here.
  };

  config = lib.mkMerge [

  ## oauth2-proxy blue/green machinery -- colour containers, boot
  ## oneshots, flip script, Caddy snippet. Gated on zitadelEnabled
  ## (oauth2-proxy is meaningless without Zitadel).
  ##
  ## `mkIf` (not `optionalAttrs`): mkIf is lazy -- the module system
  ## defers the gated value, so the condition (a `config` lookup)
  ## doesn't have to be resolved while the `config` attrset's shape is
  ## being built. `optionalAttrs` forces the condition eagerly there,
  ## which is a `config`-depends-on-`config` infinite recursion.
  (lib.mkIf zitadelEnabled oauth2ProxyBg.config)

  ## Register oauth2-proxy's runtime snippet for Caddy file-scope
  ## import (only when Zitadel -- hence oauth2-proxy -- is enabled).
  (lib.mkIf zitadelEnabled {
    homefree.internal.caddy-file-scope-imports = [ oauth2ProxyBg.caddyImportLine ];
  })

  {
    ## ── Zitadel containers via the app-platform primitive ────────────────
    ## (modules/app-platform.nix). The dns-ready ordering and ExecStartPre
    ## are generated; systemd unit overrides for extra ordering are in
    ## the escape-hatch declarations below.

    homefree.containers.zitadel = lib.mkIf zitadelEnabled {
      image = "ghcr.io/zitadel/zitadel:${zitadelVersion}";
      autoStart = true;

      ## UID 1000 is the upstream "zitadel" user -- NOT a HomeFree-managed
      ## 800-899 UID. The container runs rootful but does its own chown in
      ## preStartInit; no system user is created (createUser irrelevant for
      ## root mode).
      runAs = {
        mode = "root";
        reason = "zitadel runs as upstream UID 1000 (not HomeFree 800-899 range); data dir chowned in preStartInit";
      };

      ## zitadel does its own mkdir + chown in preStartInit -- use
      ## dataDir=null so no generated mkdir/chown runs.
      dataDir = null;

      ports = [
        "0.0.0.0:${toString zitadelPort}:8080"
      ];

      volumes = [
        "/etc/localtime:/etc/localtime:ro"
        "${zitadelDataPath}:/data"
      ];

      cmd = [
        "start-from-init"
        "--masterkeyFromEnv"
      ];

      environment = {
        TZ = config.homefree.system.timeZone;

        ZITADEL_DATABASE_POSTGRES_HOST = config.homefree.network.lan-address;
        ZITADEL_DATABASE_POSTGRES_PORT = "5432";
        ZITADEL_DATABASE_POSTGRES_DATABASE = "zitadel";
        ZITADEL_DATABASE_POSTGRES_USER_USERNAME = "zitadel";
        ## ZITADEL_DATABASE_POSTGRES_USER_PASSWORD comes from the
        ## synthesised env file (zitadelEnvFile), anchored value.
        ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE = "disable";
        ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME = "postgres";
        ## ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD comes from the
        ## synthesised env file (zitadelEnvFile), sourced from the
        ## anchored value at
        ## /var/lib/homefree-secrets/postgres/superuser-password
        ## (anchored + rotated by
        ## postgres-anchor-superuser-password.service in
        ## services/postgres). Was previously a hardcoded literal
        ## "postgres" -- see commit history if it surfaces again.
        ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE = "disable";

        ## Default-instance domain policy -- applied to BOTH the
        ## instance-default policy AND the FirstInstance org's
        ## policy at bootstrap time. Disables the `<user>@<orgdomain>`
        ## auto-suffix on usernames so the OS admin can log into
        ## Zitadel as bare "<adminUsername>". The provision script
        ## also re-asserts these via the Admin API for older
        ## Zitadel versions where DEFAULTINSTANCE didn't propagate.
        ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_USERLOGINMUSTBEDOMAIN = "false";
        ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_VALIDATEORGDOMAINS = "false";
        ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN = "false";

        ## Name the FirstInstance org "homefree" instead of the
        ## default "ZITADEL" -- gives the org a primary domain of
        ## "homefree.sso.<domain>", which reads better than
        ## "zitadel.sso.<domain>" and is consistent with the rest
        ## of the project's branding. Cosmetic; doesn't affect
        ## login (since UserLoginMustBeDomain is false above).
        ZITADEL_FIRSTINSTANCE_ORG_NAME = "homefree";

        ## First-instance human user -- bare username (the
        ## DEFAULTINSTANCE_DOMAINPOLICY above ensures the loginName
        ## isn't auto-suffixed with the org domain). Email is kept
        ## distinct so password-reset etc. work. The actual password
        ## is loaded from
        ## /var/lib/homefree-secrets/zitadel/admin-password via
        ## the env file synthesised in preStart.
        ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME = config.homefree.system.adminUsername;
        ## Prefer the explicit homefree.system.adminEmail when set
        ## (the installer captures this in the "Email" field). Fall
        ## back to the synthesized <user>@<domain> only when no
        ## email is configured. Using a synthesized email always
        ## was a bug -- downstream services like Vaultwarden key on
        ## the OIDC `email` claim, and a wrong email there causes
        ## SSO logins to either fail to match the user's existing
        ## data or to silently create a parallel empty account.
        ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS =
          if (config.homefree.system.adminEmail or "") != ""
          then config.homefree.system.adminEmail
          else "${config.homefree.system.adminUsername}@${config.homefree.system.domain}";
        ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED = "false";
        ## Pull the human's display name from the same place the
        ## OS account uses (homefree.system.adminDescription, set
        ## by the installer's "Full name" field). Split on the
        ## first space -- Zitadel requires both first and last
        ## name to be non-empty. Single-word names get "Admin"
        ## as the family name placeholder. Without this the user
        ## ends up with Zitadel's bootstrap defaults ("ZITADEL
        ## Admin") which then leaks through every OIDC client's
        ## `name` claim into Nextcloud / Forgejo / etc.
        ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME =
          let
            desc = config.homefree.system.adminDescription;
            parts = lib.splitString " " desc;
          in
            if desc == "" then "Admin" else lib.head parts;
        ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME =
          let
            desc = config.homefree.system.adminDescription;
            parts = lib.splitString " " desc;
          in
            if (builtins.length parts) > 1
            then lib.concatStringsSep " " (lib.tail parts)
            else "Admin";

        ## First-instance machine user -- long-lived PAT written to
        ## /data/pat-bootstrap (i.e. ${zitadelDataPath}/pat-bootstrap
        ## on the host). zitadel-provision.service reads this file to
        ## drive all subsequent OIDC app + machine user creation.
        ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME = "homefree-provisioner";
        ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME = "HomeFree Provisioner";
        ZITADEL_FIRSTINSTANCE_ORG_MACHINE_PAT_EXPIRATIONDATE = "2099-12-31T23:59:59Z";
        ZITADEL_FIRSTINSTANCE_ORG_MACHINE_PAT_SCOPES = "openid";
        ZITADEL_FIRSTINSTANCE_PATPATH = "/data/pat-bootstrap";

        ## Login-client machine user -- used by the zitadel-login
        ## container (Next.js) to talk to the API. PAT written to
        ## /data/bootstrap/login-client.pat on FirstInstance setup,
        ## which is the same path the login container mounts and
        ## reads as ZITADEL_SERVICE_USER_TOKEN_FILE. The role
        ## IAM_LOGIN_CLIENT is auto-assigned by Zitadel when
        ## ORG_LOGINCLIENT_* envs are set.
        ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME = "login-client";
        ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME = "HomeFree Login Client";
        ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE = "2099-12-31T23:59:59Z";
        ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH = "/data/bootstrap/login-client.pat";

        ## Force the new Login V2 UI (the only UI v4 actually
        ## ships -- there is no v1 fallback). BASEURI must be the
        ## externally-visible URL of the login container, which is
        ## /ui/v2/login/ behind Caddy on sso.<domain>.
        ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED = "true";
        ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI =
          "https://sso.${config.homefree.system.domain}/ui/v2/login/";
        ZITADEL_OIDC_DEFAULTLOGINURLV2 =
          "https://sso.${config.homefree.system.domain}/ui/v2/login/login?authRequest=";
        ZITADEL_OIDC_DEFAULTLOGOUTURLV2 =
          "https://sso.${config.homefree.system.domain}/ui/v2/login/logout?post_logout_redirect=";
        ZITADEL_SAML_DEFAULTLOGINURLV2 =
          "https://sso.${config.homefree.system.domain}/ui/v2/login/login?samlRequest=";

        ZITADEL_EXTERNALDOMAIN = "sso.${config.homefree.system.domain}";
        ZITADEL_EXTERNALPORT = "443";
        ZITADEL_EXTERNALSECURE = "true";
        ZITADEL_TLS_ENABLED = "false";
      };

      ## The synthesised env file always exists (preStartInit creates it
      ## with mode 600 even when it would be empty).
      environmentFiles = [ zitadelEnvFile ];

      ## Full zitadel preStart -- owns mkdir/chown/env-synthesis/psql.
      ## dataDir=null so the generator does NOT prepend its own mkdir.
      preStartInit = zitadelPreStart;
    };

    ## ── Zitadel Login UI container ────────────────────────────────
    ## v4 split the login UI out of the Go binary into a separate
    ## Next.js container. Without this, /ui/v2/login/* (the only
    ## login URL v4's API redirects to) returns
    ## `{"code":5, "message":"Not Found"}` and users can't log in.
    ##
    ## The login container talks to the API via the LAN address on
    ## the host's port 3241 (since both bind to the host network
    ## namespace through podman's default bridge -> host gateway).
    ## It authenticates as the "login-client" machine user using
    ## the PAT the API wrote to /data/bootstrap/login-client.pat
    ## during FirstInstance setup. We bind-mount that file into
    ## the login container at the same path.
    ##
    ## CUSTOM_REQUEST_HEADERS forces the Host header to
    ## "sso.<domain>" on every request the login UI makes back to
    ## the API. Without it, Zitadel's per-instance lookup rejects
    ## the request because the Host would be the LAN address.
    homefree.containers.zitadel-login = lib.mkIf zitadelEnabled {
      image = "ghcr.io/zitadel/zitadel-login:${zitadelVersion}";
      autoStart = true;

      ## The image's default USER is "nextjs" (uid 1001), but the
      ## API container writes login-client.pat as uid 1000 (the
      ## "zitadel" user) to a 0700 directory. Pass --user= via
      ## extraOptions so the bind-mounted bootstrap dir is readable.
      ## Both containers ignoring image-default uids is fine -- neither
      ## needs the original user's home or env, just to read/write a
      ## single mounted file tree.
      ## --network=host is required because the login container needs
      ## to call back to the API at the host's LAN address.
      runAs = {
        mode = "root";
        reason = "--user=1000:1000 is passed via extraOptions (matches API container uid); --network=host required for LAN API access";
      };

      ## No data dir to create -- the bootstrap dir is created by the
      ## zitadel (API) container's preStartInit above.
      dataDir = null;

      ## With --network=host, the `ports` mapping is ignored -- the
      ## container listens on host's port directly.
      ports = [];

      volumes = [
        "/etc/localtime:/etc/localtime:ro"
        ## Read-only -- the login container only reads the PAT, the
        ## API container writes it.
        "${zitadelBootstrapPath}:/zitadel/bootstrap:ro"
      ];

      environment = {
        TZ = config.homefree.system.timeZone;
        ## API URL is the LAN-routable Zitadel API. We pass an HTTP
        ## origin (no TLS) and rely on CUSTOM_REQUEST_HEADERS to
        ## set the Host so Zitadel's instance routing works.
        ZITADEL_API_URL = "http://${config.homefree.network.lan-address}:${toString zitadelPort}";
        NEXT_PUBLIC_BASE_PATH = "/ui/v2/login";
        ZITADEL_SERVICE_USER_TOKEN_FILE = "/zitadel/bootstrap/login-client.pat";
        CUSTOM_REQUEST_HEADERS =
          "Host:sso.${config.homefree.system.domain},X-Forwarded-Proto:https";
        ## With --network=host the Next.js server binds the host
        ## port directly. The image's default is 3000; override
        ## via PORT env to avoid colliding with anything else
        ## (AdGuard listens on 3000 in this deployment).
        PORT = toString zitadelLoginPort;
        HOSTNAME = "0.0.0.0";
      };

      extraOptions = [
        "--user=${toString zitadelContainerUid}:${toString zitadelContainerGid}"
        "--network=host"
      ];
    };

    # ── systemd unit overrides (escape hatches) ──────────────────────────
    ## These merge with the generated podman-* units from the app-platform
    ## primitive (modules/app-platform.nix) to add extra ordering that
    ## the primitive doesn't know about.

    ## Auto-generate the masterkey + oauth2-proxy cookie secret if
    ## absent. Modeled after headplane-prepare-secrets in
    ## services/headscale.nix:409-426. Runs before podman-zitadel so the
    ## env-file synthesis in zitadelPreStart finds the masterkey.
    systemd.services.zitadel-prepare-secrets = lib.mkIf zitadelEnabled {
      description = "Prepare Zitadel runtime secrets (masterkey, oauth2 cookie secret)";
      wantedBy = [ "podman-zitadel.service" ];
      before = [ "podman-zitadel.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      ## Each secret is anchored into the encrypted /etc/nixos/secrets
      ## store (lib/secrets-anchor.nix) so it survives a restore. The
      ## anchored copy is authoritative: on a restore the secret is
      ## decrypted back out rather than regenerated. Regenerating the
      ## masterkey in particular would render the backed-up Zitadel
      ## database permanently undecryptable.
      ##
      ## NOTE on adding new anchors: do NOT add them here unless the
      ## value must exist *before* podman-zitadel starts (e.g., the
      ## masterkey, which Zitadel needs at container init). For
      ## anything else, prefer zitadelPreStart (podman-zitadel's
      ## ExecStartPre) -- switch-to-configuration does NOT reliably
      ## re-run oneshot+RemainAfterExit units, so a new anchor added
      ## here may not materialise on existing instances even on a full
      ## rebuild. Container ExecStartPre always re-runs when the
      ## container restarts.
      script = zitadelPrepareSecretsScript;
    };

    ## Escape-hatch: extra ordering beyond dns-ready (generated by the
    ## primitive). podman-zitadel must also wait for the secrets oneshot
    ## and the postgres superuser password anchor.
    systemd.services.podman-zitadel = lib.mkIf zitadelEnabled {
      after = [
        "zitadel-prepare-secrets.service"
        ## Wait for the host postgres superuser password to be anchored
        ## + applied to the cluster (services/postgres). Zitadel's init
        ## container connects as `postgres` over TCP under
        ## scram-sha-256; without this ordering it would race the
        ## anchor on first boot and fail authentication.
        "postgres-anchor-superuser-password.service"
      ];
      requires = [
        "zitadel-prepare-secrets.service"
        "postgres-anchor-superuser-password.service"
      ];
    };

    ## Login UI container -- must start AFTER the API has run
    ## FirstInstance setup (so login-client.pat exists). The API is
    ## "active" as soon as the container starts but the PAT may not be
    ## written for several seconds while migrations run. We don't have
    ## a clean way to gate on that here without a healthcheck wrapper,
    ## so the login container relies on its own restart-on-failure
    ## behavior: it'll exit if the PAT file is empty/missing, systemd
    ## will retry, and once the PAT lands it succeeds.
    systemd.services.podman-zitadel-login = lib.mkIf zitadelEnabled {
      after = [ "podman-zitadel.service" ];
      wants = [ "podman-zitadel.service" ];
    };

    ## NOTE: oauth2-proxy now runs blue/green (lib/blue-green.nix --
    ## the `oauth2ProxyBg` binding in the `let` above). Its two colour
    ## containers, the secrets-check + env-synthesis ExecStartPre, the
    ## boot oneshots and the flip activation script are all generated
    ## there and merged via `oauth2ProxyBg.config`. The single
    ## `podman-oauth2-proxy` container + override that used to live
    ## here are gone.

    # ── service-config (admin UI surface) ────────────────────────────────
    # The SSO entry covers Zitadel API, Login UI, AND oauth2-proxy in
    # its systemd-service-names list. All three units are always
    # rendered when Zitadel is enabled -- oauth2-proxy refuses to
    # start until its secrets are written by the provision script,
    # so it sits in `inactive` state pre-provisioning rather than
    # being absent. The admin UI's health check should treat
    # `inactive` as not-yet-bootstrapped (NOT degraded).
    homefree.service-config = (lib.optionals zitadelEnabled [
      # User-facing SSO entry (Zitadel API + Login UI + OAuth2 Proxy
      # bundle). All three units are watched by the admin UI's health
      # check; if any one is down the SSO row goes Degraded.
      {
        inherit (config.homefree.service-options.zitadel) label name project-name;
        systemd-service-names = [
          "podman-zitadel"
          "podman-zitadel-login"
          # oauth2-proxy runs blue/green -- both colour units listed;
          # only the active one is running (standby shows inactive).
          "podman-oauth2-proxy-blue"
          "podman-oauth2-proxy-green"
        ];
        admin.show = true;
        sso = {
          kind = "infra";
          ## Dev context (intentionally not surfaced in the admin UI):
          ## Zitadel itself -- this IS the SSO IdP.
        };
        reverse-proxy = {
          enable = zitadelEnabled;
          ## Drop the legacy "zitadel" subdomain -- Zitadel v4 rejects
          ## any Host: header that doesn't match ZITADEL_EXTERNALDOMAIN
          ## with a confusing "Instance not found" JSON 500. Only the
          ## canonical "sso" subdomain is supported.
          subdomains = [ "sso" ];
          http-domains = [ "homefree.lan" config.homefree.system.localDomain ];
          https-domains = [ config.homefree.system.domain ];
          host = config.homefree.network.lan-address;
          port = zitadelPort;
          public = config.homefree.service-options.zitadel.public;
          ## Route /ui/v2/login/* to the separate Next.js login
          ## container. Everything else (incl. /ui/console, the OIDC
          ## endpoints, /debug/*) falls through the default `handle` to
          ## the API container.
          extraCaddyConfig = ''
            handle /ui/v2/login/* {
              reverse_proxy http://${config.homefree.network.lan-address}:${toString zitadelLoginPort}
            }
          '';
        };
        backup = {
          paths = [ zitadelDataPath ];
          postgres-databases = [ "zitadel" ];
        };
        ## All three OAuth2 Proxy secret fields are now auto-managed
        ## (cookie secret by zitadel-prepare-secrets, client_id +
        ## client_secret by zitadel-provision after Zitadel is healthy).
        ## They no longer appear in the admin UI as user-fillable.
        options-metadata = [
          {
            path = "enable";
            type = "bool";
            default = false;
            description = "Enable Zitadel auth service";
          }
          {
            path = "public";
            type = "bool";
            default = false;
            description = "Make service accessible from WAN";
          }
        ];
      }
    ]) ++ (lib.optionals zitadelEnabled [
      # Separate reverse-proxy entry for the auth.* subdomain -- this is
      # plumbing, not a user-facing service row, so admin.show=false.
      # Always rendered when Zitadel is enabled. Pre-provisioning
      # this proxies to a stopped oauth2-proxy and 502s; the gating
      # in services/caddy.nix's @no_auth matcher ensures users
      # aren't redirected here until the sentinel exists.
      {
        label = "oauth2proxy";
        name = "OAuth2 Proxy";
        project-name = "OAuth2 Proxy";
        systemd-service-names = [
          "podman-oauth2-proxy-blue"
          "podman-oauth2-proxy-green"
        ];
        admin.show = false;
        sso = {
          kind = "infra";
          ## Dev context (intentionally not surfaced in the admin UI):
          ## OAuth2 Proxy -- SSO gate sidecar, not a consumer.
        };
        reverse-proxy = {
          enable = true;
          subdomains = [ "auth" ];
          http-domains = [ "homefree.lan" config.homefree.system.localDomain ];
          https-domains = [ config.homefree.system.domain ];
          ## No literal host:port -- the upstream is the blue/green
          ## runtime snippet, which points at the active oauth2-proxy
          ## colour and is rewritten at flip time (no nixos-rebuild
          ## needed to change the upstream). See lib/blue-green.nix.
          upstream-snippet = "oauth2_proxy_reverse_proxy";
          ## Track the user-facing zitadel.public toggle: opening sso.<domain>
          ## externally implies auth.<domain> must be reachable too, since any
          ## public oauth2-protected service redirects unauthenticated requests
          ## to https://auth.<domain>/oauth2/start. Two endpoints, one toggle.
          public = config.homefree.service-options.zitadel.public;
        };
      }
    ]);
  }
  ];
}
