{ config, lib, pkgs, ... }:

## Default username: <adminUsername> (no orgdomain suffix — the
## zitadel-provision oneshot disables `userLoginMustBeDomain` on first run)
## Default password: pulled from /var/lib/homefree-secrets/zitadel/admin-password
## (written by the web installer in the same step that hashes the OS
## password for /etc/shadow).
##
## This module bundles Zitadel together with its companion oauth2-proxy.
## The two are always deployed as a pair — oauth2-proxy is the OIDC bridge
## that lets services that don't speak OIDC natively authenticate via
## Zitadel. Splitting them across files made cross-coupling (shared
## secrets, deploy-together gating) awkward, so they live together here.
##
## Three classes of secrets live under /var/lib/homefree-secrets/zitadel/:
##   - masterkey, oauth2-cookie-secret: auto-generated at first boot
##     by zitadel-prepare-secrets.service (no user input required)
##   - admin-password: written by the web installer
##   - oidc-client-id, oidc-client-secret: written by
##     zitadel-provision.service after Zitadel is healthy (these are
##     for the homefree-oauth2proxy OIDC app — same naming convention
##     as every other service's secrets dir)

let
  zitadelVersion = "v4.15.0";
  zitadelDataPath = "/var/lib/zitadel";
  zitadelPort = 3241;

  ## v4 split the login UI into a separate Next.js container
  ## (ghcr.io/zitadel/zitadel-login) — the API container alone
  ## responds to /ui/v2/login/* with `{"code":5, "Not Found"}`.
  ## We deploy the login container alongside the API and route
  ## /ui/v2/login/* to it via Caddy.
  zitadelLoginPort = 3242;
  ## Shared dir between API + login containers. The API writes the
  ## login-client PAT here on FirstInstance setup
  ## (ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH); the login container
  ## reads it from the same path (ZITADEL_SERVICE_USER_TOKEN_FILE).
  ## On the host, files are owned by UID 1000 (matching both
  ## containers' "zitadel" user).
  zitadelBootstrapPath = "${zitadelDataPath}/bootstrap";
  loginClientPatFile = "${zitadelBootstrapPath}/login-client.pat";

  oauth2ProxyVersion = "v7.12.0";
  oauth2ProxyPort = 4180;
  oauth2ProxyEnvFile = "/var/lib/oauth2-proxy/env";

  # Per-secret files for everything Zitadel + its bundled oauth2-proxy need.
  # See header comment for which entries are auto-generated vs installer-
  # written vs provision-script-written.
  zitadelSecretsDir = "/var/lib/homefree-secrets/zitadel";

  # oauth2-proxy reads its three required secrets from per-secret files
  # under /var/lib/homefree-secrets/zitadel/. We synthesise an env file
  # at runtime rather than baking secrets into the unit.
  #
  # Naming: cookie secret keeps its `oauth2-` prefix because it's an
  # oauth2-proxy-specific artifact (auto-generated by
  # zitadel-prepare-secrets). The client-id / client-secret use the
  # same `oidc-client-*` naming as every other service's secrets,
  # since they ARE per-service OIDC creds (the Zitadel app is just
  # called "homefree-oauth2proxy") and the provision script writes
  # them with that uniform convention.
  oauth2ProxyPreStart = ''
    mkdir -p /var/lib/oauth2-proxy
    {
      if [ -s "${zitadelSecretsDir}/oauth2-cookie-secret" ]; then
        echo "OAUTH2_PROXY_COOKIE_SECRET=$(cat "${zitadelSecretsDir}/oauth2-cookie-secret")"
      fi
      if [ -s "${zitadelSecretsDir}/oidc-client-id" ]; then
        echo "OAUTH2_PROXY_CLIENT_ID=$(cat "${zitadelSecretsDir}/oidc-client-id")"
      fi
      if [ -s "${zitadelSecretsDir}/oidc-client-secret" ]; then
        echo "OAUTH2_PROXY_CLIENT_SECRET=$(cat "${zitadelSecretsDir}/oidc-client-secret")"
      fi
    } > "${oauth2ProxyEnvFile}"
    chmod 600 "${oauth2ProxyEnvFile}"
  '';

  zitadelEnabled = config.homefree.service-options.zitadel.enable;

  # Env file synthesised at preStart so the masterkey + admin password
  # are loaded from on-disk per-secret files (auto-generated for the
  # masterkey, installer-written for the admin password).
  zitadelEnvFile = "/var/lib/zitadel/env";
  ## The Zitadel container runs as user "zitadel" (UID/GID 1000 in the
  ## upstream image). With rootful podman, that maps directly to host
  ## UID 1000, so the data directory needs to be owned/writable by
  ## that UID for the container to write /data/pat-bootstrap (and any
  ## other runtime files). Without this the FirstInstance migration
  ## fails with "open /data/pat-bootstrap: permission denied" — but
  ## not before partially populating the eventstore, which then
  ## permanently breaks subsequent retries with
  ## Errors.Instance.Domain.AlreadyExists collisions (the failed
  ## migration's partial state never rolls back).
  zitadelContainerUid = 1000;
  zitadelContainerGid = 1000;
  zitadelPreStart = ''
    set -eu
    mkdir -p ${zitadelDataPath}
    chown ${toString zitadelContainerUid}:${toString zitadelContainerGid} ${zitadelDataPath}
    chmod 700 ${zitadelDataPath}

    ## Bootstrap dir shared with the zitadel-login container. Holds the
    ## login-client PAT that the API writes on FirstInstance and that
    ## the login container reads at startup.
    mkdir -p ${zitadelBootstrapPath}
    chown ${toString zitadelContainerUid}:${toString zitadelContainerGid} ${zitadelBootstrapPath}
    chmod 700 ${zitadelBootstrapPath}

    install -m 600 /dev/null ${zitadelEnvFile}
    {
      if [ -s "${zitadelSecretsDir}/masterkey" ]; then
        echo "ZITADEL_MASTERKEY=$(cat ${zitadelSecretsDir}/masterkey)"
      fi
      if [ -s "${zitadelSecretsDir}/admin-password" ]; then
        echo "ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=$(cat ${zitadelSecretsDir}/admin-password)"
      fi
    } > ${zitadelEnvFile}
    ## env file is read by podman from the host (not the container),
    ## so it stays root:root mode 600 — only the directory itself
    ## needs to be writable by the container.
  '';

  ## (Historically there was a `deployOauth2Proxy` symbol here that
  ## gated the oauth2-proxy container on the existence of three SOPS
  ## secret files via builtins.pathExists. That gate caused a
  ## double-rebuild UX: build #1 lands the provisioning, build #2 is
  ## needed for Nix to re-eval pathExists and actually deploy
  ## oauth2-proxy. We removed it: oauth2-proxy is now always
  ## rendered when Zitadel is enabled but its ExecStartPre refuses
  ## to launch without the secrets, and zitadel-provision.service
  ## starts it once they land.)
in
{
  options.homefree.service-options.zitadel = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "enable Zitadel service";
    };

    public = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Open to public on WAN port";
    };

    label = lib.mkOption {
      type = lib.types.str;
      default = "zitadel";
      internal = true;
      description = "Service label";
    };

    name = lib.mkOption {
      type = lib.types.str;
      default = "Single Sign-on (SSO)";
      internal = true;
      description = "Service display name";
    };

    project-name = lib.mkOption {
      type = lib.types.str;
      default = "Zitadel";
      internal = true;
      description = "Project name";
    };

    ## Zitadel's secrets (masterkey, admin password, oauth2 cookie
    ## secret, OIDC client_id/secret for the oauth2-proxy app) are
    ## all auto-provisioned: zitadel-prepare-secrets.service generates
    ## the masterkey + cookie secret on first boot; the web installer
    ## sets the admin password; zitadel-provision.service mints the
    ## OAuth2 Proxy OIDC app and writes its client_id/secret. preStart
    ## scripts read the files directly from /var/lib/homefree-secrets/
    ## zitadel/, bypassing the Nix-config layer. No option declarations
    ## here.
  };

  config = {
    # ── Zitadel container ────────────────────────────────────────────────
    virtualisation.oci-containers.containers =
      (lib.optionalAttrs zitadelEnabled {
        zitadel = {
          image = "ghcr.io/zitadel/zitadel:${zitadelVersion}";

          autoStart = true;

          extraOptions = [
            # "--pull=always"
          ];

          ports = [
            "0.0.0.0:${toString zitadelPort}:8080"
          ];

          volumes = [
            "/etc/localtime:/etc/localtime:ro"
            "${zitadelDataPath}:/data"
          ];

          cmd = [
            "start-from-init"
            "--masterkeyFromEnv"
          ];

          environment = {
            TZ = config.homefree.system.timeZone;

            ZITADEL_DATABASE_POSTGRES_HOST = config.homefree.network.lan-address;
            ZITADEL_DATABASE_POSTGRES_PORT = "5432";
            ZITADEL_DATABASE_POSTGRES_DATABASE = "zitadel";
            ZITADEL_DATABASE_POSTGRES_USER_USERNAME = "zitadel";
            ZITADEL_DATABASE_POSTGRES_USER_PASSWORD = "zitadel";
            ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE = "disable";
            ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME = "postgres";
            ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD = "postgres";
            ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE = "disable";

            ## Default-instance domain policy — applied to BOTH the
            ## instance-default policy AND the FirstInstance org's
            ## policy at bootstrap time. Disables the `<user>@<orgdomain>`
            ## auto-suffix on usernames so the OS admin can log into
            ## Zitadel as bare "<adminUsername>". The provision script
            ## also re-asserts these via the Admin API for older
            ## Zitadel versions where DEFAULTINSTANCE didn't propagate.
            ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_USERLOGINMUSTBEDOMAIN = "false";
            ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_VALIDATEORGDOMAINS = "false";
            ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN = "false";

            ## Name the FirstInstance org "homefree" instead of the
            ## default "ZITADEL" — gives the org a primary domain of
            ## "homefree.sso.<domain>", which reads better than
            ## "zitadel.sso.<domain>" and is consistent with the rest
            ## of the project's branding. Cosmetic; doesn't affect
            ## login (since UserLoginMustBeDomain is false above).
            ZITADEL_FIRSTINSTANCE_ORG_NAME = "homefree";

            ## First-instance human user — bare username (the
            ## DEFAULTINSTANCE_DOMAINPOLICY above ensures the loginName
            ## isn't auto-suffixed with the org domain). Email is kept
            ## distinct so password-reset etc. work. The actual password
            ## is loaded from
            ## /var/lib/homefree-secrets/zitadel/admin-password via
            ## the env file synthesised in preStart.
            ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME = config.homefree.system.adminUsername;
            ## Prefer the explicit homefree.system.adminEmail when set
            ## (the installer captures this in the "Email" field). Fall
            ## back to the synthesized <user>@<domain> only when no
            ## email is configured. Using a synthesized email always
            ## was a bug — downstream services like Vaultwarden key on
            ## the OIDC `email` claim, and a wrong email there causes
            ## SSO logins to either fail to match the user's existing
            ## data or to silently create a parallel empty account.
            ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS =
              if (config.homefree.system.adminEmail or "") != ""
              then config.homefree.system.adminEmail
              else "${config.homefree.system.adminUsername}@${config.homefree.system.domain}";
            ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED = "false";
            ## Pull the human's display name from the same place the
            ## OS account uses (homefree.system.adminDescription, set
            ## by the installer's "Full name" field). Split on the
            ## first space — Zitadel requires both first and last
            ## name to be non-empty. Single-word names get "Admin"
            ## as the family name placeholder. Without this the user
            ## ends up with Zitadel's bootstrap defaults ("ZITADEL
            ## Admin") which then leaks through every OIDC client's
            ## `name` claim into Nextcloud / Forgejo / etc.
            ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME =
              let
                desc = config.homefree.system.adminDescription;
                parts = lib.splitString " " desc;
              in
                if desc == "" then "Admin" else lib.head parts;
            ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME =
              let
                desc = config.homefree.system.adminDescription;
                parts = lib.splitString " " desc;
              in
                if (builtins.length parts) > 1
                then lib.concatStringsSep " " (lib.tail parts)
                else "Admin";

            ## First-instance machine user — long-lived PAT written to
            ## /data/pat-bootstrap (i.e. ${zitadelDataPath}/pat-bootstrap
            ## on the host). zitadel-provision.service reads this file to
            ## drive all subsequent OIDC app + machine user creation.
            ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME = "homefree-provisioner";
            ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME = "HomeFree Provisioner";
            ZITADEL_FIRSTINSTANCE_ORG_MACHINE_PAT_EXPIRATIONDATE = "2099-12-31T23:59:59Z";
            ZITADEL_FIRSTINSTANCE_ORG_MACHINE_PAT_SCOPES = "openid";
            ZITADEL_FIRSTINSTANCE_PATPATH = "/data/pat-bootstrap";

            ## Login-client machine user — used by the zitadel-login
            ## container (Next.js) to talk to the API. PAT written to
            ## /data/bootstrap/login-client.pat on FirstInstance setup,
            ## which is the same path the login container mounts and
            ## reads as ZITADEL_SERVICE_USER_TOKEN_FILE. The role
            ## IAM_LOGIN_CLIENT is auto-assigned by Zitadel when
            ## ORG_LOGINCLIENT_* envs are set.
            ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME = "login-client";
            ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME = "HomeFree Login Client";
            ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE = "2099-12-31T23:59:59Z";
            ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH = "/data/bootstrap/login-client.pat";

            ## Force the new Login V2 UI (the only UI v4 actually
            ## ships — there is no v1 fallback). BASEURI must be the
            ## externally-visible URL of the login container, which is
            ## /ui/v2/login/ behind Caddy on sso.<domain>.
            ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED = "true";
            ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI =
              "https://sso.${config.homefree.system.domain}/ui/v2/login/";
            ZITADEL_OIDC_DEFAULTLOGINURLV2 =
              "https://sso.${config.homefree.system.domain}/ui/v2/login/login?authRequest=";
            ZITADEL_OIDC_DEFAULTLOGOUTURLV2 =
              "https://sso.${config.homefree.system.domain}/ui/v2/login/logout?post_logout_redirect=";
            ZITADEL_SAML_DEFAULTLOGINURLV2 =
              "https://sso.${config.homefree.system.domain}/ui/v2/login/login?samlRequest=";

            ZITADEL_EXTERNALDOMAIN = "sso.${config.homefree.system.domain}";
            ZITADEL_EXTERNALPORT = "443";
            ZITADEL_EXTERNALSECURE = "true";
            ZITADEL_TLS_ENABLED = "false";
          };

          ## The synthesised env file always exists (preStart creates it
          ## with mode 600 even when it would be empty).
          environmentFiles = [ zitadelEnvFile ];
        };

        # ── Zitadel Login UI container ────────────────────────────────
        ## v4 split the login UI out of the Go binary into a separate
        ## Next.js container. Without this, /ui/v2/login/* (the only
        ## login URL v4's API redirects to) returns
        ## `{"code":5, "message":"Not Found"}` and users can't log in.
        ##
        ## The login container talks to the API via the LAN address on
        ## the host's port 3241 (since both bind to the host network
        ## namespace through podman's default bridge → host gateway).
        ## It authenticates as the "login-client" machine user using
        ## the PAT the API wrote to /data/bootstrap/login-client.pat
        ## during FirstInstance setup. We bind-mount that file into
        ## the login container at the same path.
        ##
        ## CUSTOM_REQUEST_HEADERS forces the Host header to
        ## "sso.<domain>" on every request the login UI makes back to
        ## the API. Without it, Zitadel's per-instance lookup rejects
        ## the request because the Host would be the LAN address.
        zitadel-login = {
          image = "ghcr.io/zitadel/zitadel-login:${zitadelVersion}";
          autoStart = true;
          ## The image's default USER is "nextjs" (uid 1001), but the
          ## API container writes login-client.pat as uid 1000 (the
          ## "zitadel" user) to a 0700 directory. Run the login
          ## container as the same uid so the bind-mounted bootstrap
          ## dir is readable. Both containers ignoring image-default
          ## uids is fine — neither needs the original user's home or
          ## env, just to read/write a single mounted file tree.
          ##
          ## --network=host is required because the login container
          ## needs to call back to the API at the host's LAN address
          ## (zitadel-api isn't reachable through podman's default
          ## bridge — same reason oauth2-proxy uses host networking
          ## further down this file).
          extraOptions = [
            "--user=${toString zitadelContainerUid}:${toString zitadelContainerGid}"
            "--network=host"
          ];
          ## With --network=host, the `ports` mapping is ignored — the
          ## container listens on host's port 3000 directly. Override
          ## that to our chosen port via env so the listener binds
          ## somewhere we control (avoiding collision with anything
          ## else that wants 3000 on the host).
          ports = [];
          volumes = [
            "/etc/localtime:/etc/localtime:ro"
            ## Read-only — the login container only reads the PAT, the
            ## API container writes it.
            "${zitadelBootstrapPath}:/zitadel/bootstrap:ro"
          ];
          environment = {
            TZ = config.homefree.system.timeZone;
            ## API URL is the LAN-routable Zitadel API. We pass an HTTP
            ## origin (no TLS) and rely on CUSTOM_REQUEST_HEADERS to
            ## set the Host so Zitadel's instance routing works.
            ZITADEL_API_URL = "http://${config.homefree.network.lan-address}:${toString zitadelPort}";
            NEXT_PUBLIC_BASE_PATH = "/ui/v2/login";
            ZITADEL_SERVICE_USER_TOKEN_FILE = "/zitadel/bootstrap/login-client.pat";
            CUSTOM_REQUEST_HEADERS =
              "Host:sso.${config.homefree.system.domain},X-Forwarded-Proto:https";
            ## With --network=host the Next.js server binds the host
            ## port directly. The image's default is 3000; override
            ## via PORT env to avoid colliding with anything else
            ## (AdGuard listens on 3000 in this deployment).
            PORT = toString zitadelLoginPort;
            HOSTNAME = "0.0.0.0";
          };
        };
      })
      # ── OAuth2 Proxy container ──────────────────────────────────────
      ## We always RENDER the oauth2-proxy container into the system,
      ## but we don't auto-start it (autoStart=false) — its
      ## ExecStartPre refuses to launch until the three secret files
      ## have been written by zitadel-provision.service. The
      ## provision script then `systemctl start`s it once the secrets
      ## land. This avoids the double-rebuild that an `optionalAttrs
      ## deployOauth2Proxy` gate would require (since the gate uses
      ## builtins.pathExists, evaluated at build time).
      // (lib.optionalAttrs zitadelEnabled {
        oauth2-proxy = {
          image = "oauth2-proxy/oauth2-proxy:${oauth2ProxyVersion}";

          ## Don't auto-start — gated on the secret files existing
          ## (see ExecStartPre check in the systemd unit override
          ## below). Once provisioning lands, the script kicks it.
          autoStart = false;

          extraOptions = [
            # @TODO: Is host networking actually necessary?
            "--network=host"
          ];

          ports = [
            "0.0.0.0:${toString oauth2ProxyPort}:${toString oauth2ProxyPort}"
          ];

          volumes = [
            "/etc/localtime:/etc/localtime:ro"
          ];

          environment = {
            TZ = config.homefree.system.timeZone;
            OAUTH2_PROXY_PROVIDER = "oidc";
            OAUTH2_PROXY_OIDC_ISSUER_URL = "https://sso.${config.homefree.system.domain}";
            OAUTH2_PROXY_REDIRECT_URL = "https://auth.${config.homefree.system.domain}/oauth2/callback";
            OAUTH2_PROXY_EMAIL_DOMAINS = "*";
            OAUTH2_PROXY_COOKIE_DOMAINS = ".${config.homefree.system.domain}";
            OAUTH2_PROXY_WHITELIST_DOMAINS = ".${config.homefree.system.domain}";
            OAUTH2_PROXY_HTTP_ADDRESS = "0.0.0.0:${toString oauth2ProxyPort}";
            OAUTH2_PROXY_REVERSE_PROXY = "true";
            OAUTH2_PROXY_COOKIE_SECURE = "true";
            OAUTH2_PROXY_COOKIE_HTTPONLY = "true";
            ## `urn:zitadel:iam:org:project:roles` asks Zitadel to
            ## embed the user's homefree-project roles in the id
            ## token under `urn:zitadel:iam:org:project:roles`. We
            ## then surface those to downstream services as the
            ## `groups` claim (OAUTH2_PROXY_OIDC_GROUPS_CLAIM below),
            ## which is what most services natively understand for
            ## admin-vs-user mapping.
            OAUTH2_PROXY_SCOPE = "openid email profile urn:zitadel:iam:org:project:roles";

            ## Pull the role list out of Zitadel's namespaced claim
            ## and re-emit it under the standard `groups` claim. The
            ## namespaced claim is an *object* keyed by role name (each
            ## value is a per-org map), not a flat array; oauth2-proxy
            ## handles both, taking the keys when it sees the object
            ## form.
            OAUTH2_PROXY_OIDC_GROUPS_CLAIM =
              "urn:zitadel:iam:org:project:roles";

            ## Admin-only gate at the oauth2-proxy layer is DISABLED
            ## for now. We tried `OAUTH2_PROXY_ALLOWED_GROUPS =
            ## "homefree-admin"`, but Zitadel's role claim
            ## (urn:zitadel:iam:org:project:roles) is an OBJECT whose
            ## keys are role names — not a string array — and
            ## oauth2-proxy v7's group parser doesn't extract keys
            ## from that shape. The result: oauth2-proxy sees no
            ## groups and 403s everyone.
            ##
            ## Workaround in flight: a Zitadel Action that flattens
            ## the role-keys list into a standard `groups` claim
            ## array. Once that lands, set ALLOWED_GROUPS back on.
            ##
            ## In the meantime, admin gating happens in the FastAPI
            ## middleware (TrustedHeaderAuthMiddleware in
            ## simple_main.py) which CAN parse the namespaced
            ## claim. The admin UI is therefore still admin-only.
            ## AdGuard / WebDAV are open to any authenticated user
            ## until the flattening action is deployed — known gap.
            # OAUTH2_PROXY_ALLOWED_GROUPS = "homefree-admin";

            ## Caddy serves https://sso.<domain> with a cert from its
            ## built-in "Caddy Local Authority" CA, which isn't in the
            ## system trust store. oauth2-proxy needs to fetch
            ## /.well-known/openid-configuration on startup and would
            ## fail with `tls: x509: certificate signed by unknown
            ## authority`. We're talking to ourselves over a local
            ## bridge — skip verify is safe here. (Alternatives:
            ## point at http://<lan>:3241 directly, but then the
            ## issuer URL Zitadel embeds in tokens won't match what
            ## oauth2-proxy expects, breaking validation.)
            OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY = "true";
            OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION = "false";

            ## Needed to prevent Zitadel from blocking due to user-agent
            ## headers being different between proxy and upstream.
            OAUTH2_PROXY_PASS_USER_HEADERS = "true";
            OAUTH2_PROXY_SET_AUTHORIZATION_HEADER = "true";

            ## Required for Caddy's `forward_auth ... copy_headers
            ## X-Auth-Request-User ...` to actually have something
            ## to copy. Without this, the /oauth2/auth response
            ## returns 200 on success but with NO X-Auth-Request-*
            ## headers — Caddy then proxies the request to the
            ## backend with no auth header, and the FastAPI middle-
            ## ware in web-platform/backend/simple_main.py rejects
            ## with "missing X-Auth-Request-User".
            ##
            ## PASS_USER_HEADERS (above) only emits headers when
            ## oauth2-proxy itself proxies the request through to
            ## an upstream. SET_XAUTHREQUEST is the orthogonal flag
            ## that emits the same headers on the auth-only
            ## endpoint /oauth2/auth, which is what Caddy's
            ## forward_auth uses.
            OAUTH2_PROXY_SET_XAUTHREQUEST = "true";

            ## Source the X-Auth-Request-User value from the OIDC
            ## `preferred_username` claim — Zitadel sets this to
            ## the bare username we configured (e.g. "erahhal"),
            ## matching /var/lib/homefree-admin/admin-username
            ## that the FastAPI middleware compares against.
            ##
            ## Without this oauth2-proxy defaults to the OIDC `sub`
            ## claim, which is Zitadel's numeric internal user ID
            ## ("372411477086899193") — never matches the OS-side
            ## admin username, so every authenticated request gets
            ## 403 "not the admin user".
            OAUTH2_PROXY_OIDC_EMAIL_CLAIM = "email";
            OAUTH2_PROXY_USER_ID_CLAIM = "preferred_username";
          };

          # Env file is synthesised by the prestart from the SOPS-managed
          # secrets in /var/lib/homefree-secrets/zitadel/.
          environmentFiles = [ oauth2ProxyEnvFile ];
        };
      });

    # ── systemd unit overrides ───────────────────────────────────────────

    ## Auto-generate the masterkey + oauth2-proxy cookie secret if
    ## absent. Modeled after headplane-prepare-secrets in
    ## services/headscale.nix:409-426. Runs before podman-zitadel so the
    ## env-file synthesis in zitadelPreStart finds the masterkey.
    systemd.services.zitadel-prepare-secrets = lib.mkIf zitadelEnabled {
      description = "Prepare Zitadel runtime secrets (masterkey, oauth2 cookie secret)";
      wantedBy = [ "podman-zitadel.service" ];
      before = [ "podman-zitadel.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        set -eu
        mkdir -p ${zitadelSecretsDir}
        chmod 700 ${zitadelSecretsDir}

        if [ ! -s "${zitadelSecretsDir}/masterkey" ]; then
          ## Zitadel's masterkey must be exactly 32 bytes. Hex output of
          ## `openssl rand -hex 16` is 32 ASCII characters → 32 bytes,
          ## and avoids the base64 padding/`=` issue that breaks
          ## ZITADEL_MASTERKEY parsing in some shells.
          ${pkgs.openssl}/bin/openssl rand -hex 16 \
            > "${zitadelSecretsDir}/masterkey"
        fi
        chmod 600 "${zitadelSecretsDir}/masterkey"

        if [ ! -s "${zitadelSecretsDir}/oauth2-cookie-secret" ]; then
          ${pkgs.openssl}/bin/openssl rand -base64 32 | head -c 32 \
            > "${zitadelSecretsDir}/oauth2-cookie-secret"
        fi
        chmod 600 "${zitadelSecretsDir}/oauth2-cookie-secret"
      '';
    };

    systemd.services.podman-zitadel = lib.optionalAttrs zitadelEnabled {
      after = [ "dns-ready.service" "zitadel-prepare-secrets.service" ];
      requires = [ "dns-ready.service" "zitadel-prepare-secrets.service" ];
      serviceConfig = {
        ExecStartPre = [ "!${pkgs.writeShellScript "zitadel-prestart" zitadelPreStart}" ];
      };
    };

    ## Login UI container — must start AFTER the API has run
    ## FirstInstance setup (so login-client.pat exists). The API is
    ## "active" as soon as the container starts but the PAT may not be
    ## written for several seconds while migrations run. We don't have
    ## a clean way to gate on that here without a healthcheck wrapper,
    ## so the login container relies on its own restart-on-failure
    ## behavior: it'll exit if the PAT file is empty/missing, systemd
    ## will retry, and once the PAT lands it succeeds.
    systemd.services.podman-zitadel-login = lib.mkIf zitadelEnabled {
      after = [ "dns-ready.service" "podman-zitadel.service" ];
      requires = [ "dns-ready.service" ];
      wants = [ "podman-zitadel.service" ];
    };

    ## oauth2-proxy unit is always rendered when Zitadel is enabled,
    ## but its ExecStartPre refuses to launch until the three secret
    ## files have been written by zitadel-provision.service. The
    ## provision script `systemctl start`s it once the secrets land.
    systemd.services.podman-oauth2-proxy = lib.optionalAttrs zitadelEnabled {
      after = [ "dns-ready.service" "zitadel-prepare-secrets.service" ];
      requires = [ "dns-ready.service" "zitadel-prepare-secrets.service" ];
      serviceConfig = {
        ## Refuse to start if the OIDC client_id/client_secret aren't
        ## on disk yet — oauth2-proxy crash-loops without them, and
        ## crash-looping past StartLimitBurst trips a permanent
        ## failure that needs `systemctl reset-failed` to recover.
        ExecStartPre = [
          "!${pkgs.writeShellScript "oauth2-proxy-secrets-check" ''
            for f in oauth2-cookie-secret oidc-client-id oidc-client-secret; do
              if [ ! -s "${zitadelSecretsDir}/$f" ]; then
                echo "oauth2-proxy: ${zitadelSecretsDir}/$f missing or empty — refusing to start" >&2
                exit 1
              fi
            done
          ''}"
          "!${pkgs.writeShellScript "oauth2-proxy-prestart" oauth2ProxyPreStart}"
        ];
      };
    };

    # ── service-config (admin UI surface) ────────────────────────────────
    # The SSO entry covers Zitadel API, Login UI, AND oauth2-proxy in
    # its systemd-service-names list. All three units are always
    # rendered when Zitadel is enabled — oauth2-proxy refuses to
    # start until its secrets are written by the provision script,
    # so it sits in `inactive` state pre-provisioning rather than
    # being absent. The admin UI's health check should treat
    # `inactive` as not-yet-bootstrapped (NOT degraded).
    homefree.service-config = (lib.optionals zitadelEnabled [
      # User-facing SSO entry (Zitadel API + Login UI + OAuth2 Proxy
      # bundle). All three units are watched by the admin UI's health
      # check; if any one is down the SSO row goes Degraded.
      {
        inherit (config.homefree.service-options.zitadel) label name project-name;
        systemd-service-names = [
          "podman-zitadel"
          "podman-zitadel-login"
          "podman-oauth2-proxy"
        ];
        admin.show = true;
        sso = {
          kind = "infra";
          notes = "Zitadel itself — this IS the SSO IdP.";
        };
        reverse-proxy = {
          enable = zitadelEnabled;
          ## Drop the legacy "zitadel" subdomain — Zitadel v4 rejects
          ## any Host: header that doesn't match ZITADEL_EXTERNALDOMAIN
          ## with a confusing "Instance not found" JSON 500. Only the
          ## canonical "sso" subdomain is supported.
          subdomains = [ "sso" ];
          http-domains = [ "homefree.lan" config.homefree.system.localDomain ];
          https-domains = [ config.homefree.system.domain ];
          host = config.homefree.network.lan-address;
          port = zitadelPort;
          public = config.homefree.service-options.zitadel.public;
          ## Route /ui/v2/login/* to the separate Next.js login
          ## container. Everything else (incl. /ui/console, the OIDC
          ## endpoints, /debug/*) falls through the default `handle` to
          ## the API container.
          extraCaddyConfig = ''
            handle /ui/v2/login/* {
              reverse_proxy http://${config.homefree.network.lan-address}:${toString zitadelLoginPort}
            }
          '';
        };
        backup = {
          paths = [ zitadelDataPath ];
          postgres-databases = [ "zitadel" ];
        };
        ## All three OAuth2 Proxy secret fields are now auto-managed
        ## (cookie secret by zitadel-prepare-secrets, client_id +
        ## client_secret by zitadel-provision after Zitadel is healthy).
        ## They no longer appear in the admin UI as user-fillable.
        options-metadata = [
          {
            path = "enable";
            type = "bool";
            default = false;
            description = "Enable Zitadel auth service";
          }
          {
            path = "public";
            type = "bool";
            default = false;
            description = "Make service accessible from WAN";
          }
        ];
      }
    ]) ++ (lib.optionals zitadelEnabled [
      # Separate reverse-proxy entry for the auth.* subdomain — this is
      # plumbing, not a user-facing service row, so admin.show=false.
      # Always rendered when Zitadel is enabled. Pre-provisioning
      # this proxies to a stopped oauth2-proxy and 502s; the gating
      # in services/caddy.nix's @no_auth matcher ensures users
      # aren't redirected here until the sentinel exists.
      {
        label = "oauth2proxy";
        name = "OAuth2 Proxy";
        project-name = "OAuth2 Proxy";
        systemd-service-names = [ "podman-oauth2-proxy" ];
        admin.show = false;
        sso = {
          kind = "infra";
          notes = "OAuth2 Proxy — SSO gate sidecar, not a consumer.";
        };
        reverse-proxy = {
          enable = true;
          subdomains = [ "auth" ];
          http-domains = [ "homefree.lan" config.homefree.system.localDomain ];
          https-domains = [ config.homefree.system.domain ];
          host = config.homefree.network.lan-address;
          port = oauth2ProxyPort;
          public = false;
        };
      }
    ]);
  };
}
