"""
DiskoConfigBuilder - generates a disko.nix module from the installer's
partitioning selection.

The generated module is used twice:
  1. At install time, `disko --mode destroy,format,mount` reads it to
     destructively partition / LUKS-format / open / mkfs / mount the
     target disks under /mnt.
  2. It is imported into the installed system's flake, so disko derives
     `fileSystems`, `boot.initrd.luks.devices`, and `swapDevices` from
     the exact same source of truth (no hardware-config drift).

Layout decisions (see the implementation plan):
  - btrfs everywhere, subvolumes @, @home, @nix (compress=zstd, noatime).
  - RAID is btrfs-native (raid1/raid0). LUKS is applied per physical
    disk; the btrfs raid spans the resulting /dev/mapper devices.
  - LUKS `settings.crypttabExtraOpts` carries `tpm2-device=auto
    tpm2-pcrs=7` from day one. Until the first-boot service enrolls a
    TPM2 keyslot, systemd's initrd falls back to the passphrase prompt.
  - Swap: one (optionally encrypted) swap partition per disk, no RAID.

disko multi-device btrfs note: disko formats disks in alphabetical
order by attribute name, and a multi-device btrfs can only be created
once every member device exists. So the btrfs filesystem is declared on
the *last* disk; earlier disks expose a bare LUKS mapper (no inner
content). The last disk's `extraArgs` lists the earlier mapper paths.
This mirrors disko's own example/luks-btrfs-raid.nix.
"""

from typing import List


# Path of the install-time keyfile, as seen *inside the installed system*.
# disko uses `settings.keyFile` both to luksFormat at install time and to
# generate the persisted crypttab entry. The first-boot TPM2-enroll
# service adds a TPM2 keyslot and then shreds this file.
LUKS_KEYFILE = "/etc/nixos/secrets/luks.key"

# btrfs subvolume -> mountpoint map, shared by every layout.
SUBVOLUMES = {
    "@": "/",
    "@home": "/home",
    "@nix": "/nix",
}


class DiskoConfigBuilder:
    """Builds the textual contents of /etc/nixos/disko.nix."""

    def __init__(
        self,
        disks: List[str],
        raid: str = "none",
        use_encryption: bool = True,
        use_swap: bool = True,
        swap_size_mb: int = 0,
    ):
        if not disks:
            raise ValueError("DiskoConfigBuilder requires at least one disk")
        if raid in ("raid0", "raid1") and len(disks) < 2:
            raise ValueError(f"{raid} requires at least 2 disks")
        if raid not in ("none", "raid0", "raid1"):
            raise ValueError(f"Unknown raid level: {raid}")

        self.disks = disks
        self.raid = raid
        self.use_encryption = use_encryption
        self.use_swap = use_swap
        # swap_size_mb 0 => caller didn't size it; default to 8G per disk.
        self.swap_size_mb = swap_size_mb or 8192

    # -- public API --------------------------------------------------

    @property
    def is_raid(self) -> bool:
        return self.raid in ("raid0", "raid1") and len(self.disks) >= 2

    def luks_device_names(self) -> List[str]:
        """Mapper names for every LUKS container (root + swap).

        The first-boot TPM2-enroll service iterates these to enroll a
        keyslot per container. Order: roots first, then swaps.
        """
        if not self.use_encryption:
            return []
        names = list(self._root_mapper_names())
        if self.use_swap:
            names += [f"cryptswap{i + 1}" for i in range(len(self.disks))]
        return names

    def build(self) -> str:
        """Render the full disko.nix file as a string."""
        header = (
            "# Generated by the HomeFree installer - do not edit by hand.\n"
            "# Consumed by `disko` at install time and imported into the\n"
            "# installed system so fileSystems / luks / swap are all\n"
            "# derived from this single source of truth.\n"
            "{\n"
            "  disko.devices = {\n"
            "    disk = {\n"
        )
        body = "".join(self._render_disk(i) for i in range(len(self.disks)))
        footer = "    };\n  };\n}\n"
        return header + body + footer

    # -- internals ---------------------------------------------------

    def _root_mapper_names(self) -> List[str]:
        """LUKS mapper names for the root containers, one per disk."""
        if self.is_raid:
            return [f"cryptd{i + 1}" for i in range(len(self.disks))]
        return ["cryptroot"]

    def root_partlabels(self) -> List[str]:
        """GPT partlabels disko assigns to the root partitions.

        disko's default label is `<parentType>-<diskName>-<partName>`.
        We set each disk's `name` to `d<N>` and the root partition's
        `name`/`label` to `root`, so the label is `disk-dN-root`.
        """
        return [f"disk-d{i + 1}-root" for i in range(len(self.disks))]

    def swap_partlabels(self) -> List[str]:
        """GPT partlabels for the swap partitions (one per disk)."""
        return [f"disk-d{i + 1}-swap" for i in range(len(self.disks))]

    def _btrfs_member_paths(self) -> List[str]:
        """Device paths btrfs raid spans, in disk order.

        Encrypted -> /dev/mapper names. Plain -> stable by-partlabel
        paths.
        """
        if self.use_encryption:
            return [f"/dev/mapper/{n}" for n in self._root_mapper_names()]
        return [f"/dev/disk/by-partlabel/{lbl}"
                for lbl in self.root_partlabels()]

    def _btrfs_subvolumes_block(self, indent: str) -> str:
        lines = []
        for subvol, mount in SUBVOLUMES.items():
            lines.append(
                f'{indent}"{subvol}" = {{ mountpoint = "{mount}"; '
                f'mountOptions = [ "compress=zstd" "noatime" ]; }};'
            )
        return "\n".join(lines)

    def _btrfs_extra_args(self) -> str:
        """`extraArgs` for the single mkfs.btrfs that builds the array.

        Runs on the LAST disk. For RAID it also lists every *earlier*
        member device so one mkfs builds the whole array.
        """
        args = ['"-f"', '"-L nixos"']
        if self.is_raid:
            data = "raid1" if self.raid == "raid1" else "raid0"
            # Metadata stays raid1 even for raid0 data - btrfs best
            # practice, cheap, and protects the filesystem trees.
            args += [f'"-d {data}"', '"-m raid1"']
            # All members except the last (the last is `config.device`,
            # which disko passes implicitly to mkfs.btrfs).
            for dev in self._btrfs_member_paths()[:-1]:
                args.append(f'"{dev}"')
        return "[ " + " ".join(args) + " ]"

    def _btrfs_content_block(self, indent: str) -> str:
        """The `type = "btrfs"` content - emitted on the last disk only."""
        return (
            f"{indent}content = {{\n"
            f'{indent}  type = "btrfs";\n'
            f"{indent}  extraArgs = {self._btrfs_extra_args()};\n"
            f"{indent}  subvolumes = {{\n"
            f"{self._btrfs_subvolumes_block(indent + '    ')}\n"
            f"{indent}  }};\n"
            f"{indent}}};\n"
        )

    def _luks_settings_block(self, indent: str) -> str:
        """LUKS attributes for a `type = "luks"` content block.

        Uses `passwordFile` (NOT `settings.keyFile`) for the install-time
        keyfile: disko reads `passwordFile` to luksFormat/luksOpen but
        does NOT persist it into the installed system's crypttab. That is
        what we want - the installed system must unlock via TPM2 (once
        enrolled) or the recovery passphrase, never an on-disk keyfile.

        `settings` carries only what *should* persist into
        boot.initrd.luks.devices.<name>: TPM2 crypttab opts + discards.
        """
        return (
            f'{indent}passwordFile = "{LUKS_KEYFILE}";\n'
            f"{indent}settings = {{\n"
            f"{indent}  allowDiscards = true;\n"
            f"{indent}  # TPM2 auto-unlock; the initrd falls back to the\n"
            f"{indent}  # recovery passphrase until a slot is enrolled.\n"
            f'{indent}  crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-pcrs=7" ];\n'
            f"{indent}}};\n"
        )

    def _render_root_partition(self, disk_index: int) -> str:
        """The root partition entry for a given disk.

        - Plain, single disk: btrfs directly in the partition.
        - Plain, RAID: bare labelled partitions; the last carries btrfs.
        - Encrypted: a LUKS container; the last disk's LUKS carries
          btrfs, earlier disks' LUKS are bare mappers.
        """
        i = disk_index
        is_last = i == len(self.disks) - 1

        # An explicit `label` makes the GPT partlabel deterministic
        # (disko default: `disk-<diskName>-<partName>`), so the
        # by-partlabel path is stable for btrfs members and cryptsetup.
        label_line = f'            label = "disk-d{i + 1}-root";\n'

        if not self.use_encryption:
            if self.is_raid:
                # Bare labelled partition; last one declares the btrfs.
                inner = ""
                if is_last:
                    inner = self._btrfs_content_block("            ")
                return (
                    f'          root = {{\n'
                    f'            size = "100%";\n'
                    f"{label_line}"
                    f"{inner}"
                    f'          }};\n'
                )
            # Single plain disk: btrfs straight in the partition.
            return (
                '          root = {\n'
                '            size = "100%";\n'
                f"{label_line}"
                f"{self._btrfs_content_block('            ')}"
                '          };\n'
            )

        # Encrypted path.
        name = (f"cryptd{i + 1}" if self.is_raid else "cryptroot")
        block = (
            '          root = {\n'
            '            size = "100%";\n'
            f"{label_line}"
            '            content = {\n'
            '              type = "luks";\n'
            f'              name = "{name}";\n'
            f"{self._luks_settings_block('              ')}"
        )
        if is_last:
            block += self._btrfs_content_block("              ")
        # Earlier RAID members: bare LUKS mapper, no inner content -
        # adopted as a btrfs member by the last disk's mkfs.
        block += (
            '            };\n'
            '          };\n'
        )
        return block

    def _render_swap_partition(self, disk_index: int) -> str:
        if not self.use_swap:
            return ""
        i = disk_index
        if self.use_encryption:
            inner = (
                '            content = {\n'
                '              type = "luks";\n'
                f'              name = "cryptswap{i + 1}";\n'
                f"{self._luks_settings_block('              ')}"
                '              content = {\n'
                '                type = "swap";\n'
                '              };\n'
                '            };\n'
            )
        else:
            inner = (
                '            content = {\n'
                '              type = "swap";\n'
                '            };\n'
            )
        return (
            '          swap = {\n'
            f'            size = "{self.swap_size_mb}M";\n'
            f'            label = "disk-d{i + 1}-swap";\n'
            f"{inner}"
            '          };\n'
        )

    def _render_disk(self, disk_index: int) -> str:
        i = disk_index
        device = self.disks[i]
        key = f"d{i + 1}"
        is_first = i == 0

        partitions = []

        # ESP on disk 1 (primary -> /boot). On RAID a second ESP is
        # created on disk 2 for resilience, mounted at /boot2 as a
        # best-effort mirror.
        if is_first:
            esp_mount = "/boot"
        elif i == 1 and self.is_raid:
            esp_mount = "/boot2"
        else:
            esp_mount = None
        if esp_mount:
            # 1M BIOS-boot partition (EF02) ahead of the ESP. Inert on a
            # UEFI install, but when the ISO was booted in legacy BIOS
            # mode the generated config installs GRUB for i386-pc, and
            # grub-install on a GPT disk has nowhere to embed core.img
            # without one ("embedding won't be possible") — the install
            # then dies at the bootloader step. KVM/cockpit VMs default
            # to SeaBIOS, so the BIOS path is common in practice.
            partitions.append(
                '          boot = {\n'
                '            size = "1M";\n'
                '            type = "EF02";\n'
                # Nix attrsets sort alphabetically; disko orders
                # partition creation by priority, so pin the BIOS-boot
                # stub to the front of the disk (upstream disko
                # convention for EF02).
                '            priority = 1;\n'
                '          };\n'
            )
            partitions.append(
                '          ESP = {\n'
                '            size = "512M";\n'
                '            type = "EF00";\n'
                '            content = {\n'
                '              type = "filesystem";\n'
                '              format = "vfat";\n'
                f'              mountpoint = "{esp_mount}";\n'
                '              mountOptions = [ "umask=0077" ];\n'
                '            };\n'
                '          };\n'
            )

        partitions.append(self._render_swap_partition(i))
        partitions.append(self._render_root_partition(i))

        # Re-indent partition blocks by two spaces so they nest cleanly
        # under `partitions = {`. Purely cosmetic - Nix ignores layout.
        body = "".join(partitions)
        body = "\n".join(
            ("  " + ln) if ln else ln for ln in body.split("\n")
        )

        return (
            f"      {key} = {{\n"
            f'        type = "disk";\n'
            # Explicit name -> deterministic partlabels (disko default
            # label is `disk-<name>-<partName>`).
            f'        name = "{key}";\n'
            f'        device = "{device}";\n'
            f"        content = {{\n"
            f'          type = "gpt";\n'
            f"          partitions = {{\n"
            f"{body}"
            f"          }};\n"
            f"        }};\n"
            f"      }};\n"
        )
