"""
Installation service - handles the actual NixOS installation process
Ported from Calamares nixos module
"""

import os
import subprocess
import threading
import logging
import psutil
from pathlib import Path
from typing import Dict, Any, Optional

import base64
import secrets
import string

from services.config import ConfigService
from services.network import NetworkService
from services.disko_builder import DiskoConfigBuilder, LUKS_KEYFILE
from utils.privileged import run_privileged, popen_privileged, write_file_privileged, mkdir_privileged

logger = logging.getLogger(__name__)

# Pinned lanzaboote revision - must match the flake input in the repo
# root flake.nix. Used only when the user opts into Secure Boot.
LANZABOOTE_FLAKE_REF = "github:nix-community/lanzaboote/v0.4.3"


class InstallationService:
    """Service for managing the NixOS installation process"""

    _status: Dict[str, Any] = {
        'step': 'Not started',
        'progress': 0.0,
        'message': '',
        'completed': False,
        'error': None,
    }

    _install_thread: Optional[threading.Thread] = None
    _running = False

    # Set during partitioning; surfaced to the UI completion screen.
    _recovery_passphrase: Optional[str] = None
    # The DiskoConfigBuilder used for this install, kept so later steps
    # (config generation) can query the LUKS layout.
    _disko_builder: Optional[Any] = None

    # Templates for configuration files
    #
    # Note: the disko *module* is NOT imported here - the HomeFree base
    # flake already imports `disko.nixosModules.disko` (see its
    # default.nix). Importing it again would define `_module.args.diskoLib`
    # twice and fail evaluation. We only import the generated ./disko.nix
    # config file (in configuration.nix), which sets `disko.devices` on
    # the module HomeFree base already provides.
    FLAKE_TEMPLATE = """{
  description = "HomeFree NixOS Configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    homefree-base.url = "git+https://git.homefree.host/homefree/homefree.git";@@lanzaboote_input@@
    # >>> homefree-base-override (managed - do not edit by hand) >>>@@base_override_region@@
    # <<< homefree-base-override <<<
    # >>> homefree-developers-inputs (managed - do not edit by hand) >>>
    homefree-navidrome.url = "git+https://git.homefree.host/homefree/homefree-navidrome.git";
    # <<< homefree-developers-inputs <<<
  };

  outputs = { self, nixpkgs, homefree-base@@lanzaboote_output_arg@@, ... }@inputs:
  let
    system = "x86_64-linux";
    # Custom developer flakes registered via the admin panel's
    # Developers section. `custom-flakes.nix` is regenerated by the
    # admin backend from homefree-config.json — never edit it by hand.
    # The pathExists guard keeps the build working when no flakes are
    # registered (the file may be absent on older installs).
    customFlakeModules =
      if builtins.pathExists ./custom-flakes.nix
      then import ./custom-flakes.nix { inherit inputs; }
      else [];
    # `homefree` selects which input the build uses for the HomeFree
    # base: the official `homefree-base`, or an alternate repo enabled
    # via the admin panel's Developers section. The admin backend
    # rewrites the region below — never edit it by hand.
    # >>> homefree-base-binding (managed - do not edit by hand) >>>
    homefree = inputs.@@base_binding_target@@;
    # <<< homefree-base-binding <<<
    # Per-instance config. homefree-config.json is the single source of
    # truth; the admin UI / installer write it. The shared homefree repo
    # module homefree-config-loader maps this parsed data into homefree.*
    # — there is NO generated homefree-configuration.nix anymore (the old
    # model went stale on a bare `nixos-rebuild switch`). We pass the
    # parsed JSON and this directory (for the mediawiki logo-path import,
    # which must resolve user assets under /etc/nixos) into the module
    # system via specialArgs.
    homefreeConfigJson = builtins.fromJSON (builtins.readFile ./homefree-config.json);
  in {
    nixosConfigurations = {
      @@hostname@@ = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          homefree.nixosModules.homefree@@lanzaboote_module@@
          homefree.nixosModules.homefree-config-loader
          ./configuration.nix
        ] ++ customFlakeModules;
        specialArgs = {
          inherit system;
          homefree-inputs = homefree.inputs;
          inherit homefreeConfigJson;
          homefreeInstanceDir = ./.;
        };
      };
    };
  };
}
"""

    # Side file imported by flake.nix. Regenerated by DevelopersService
    # whenever the registered flake set changes. The form below stamps
    # the default plugins shipped on a fresh install — it must stay
    # consistent with the `developers.flakes` list in
    # HOMEFREE_JSON_TEMPLATE and the inputs region of FLAKE_TEMPLATE
    # (one `(inputs.<inputName>.nixosModules.<moduleAttr>)` line per
    # enabled flake). DevelopersService rewrites this file from
    # homefree-config.json the first time the admin panel touches the
    # flake set.
    CUSTOM_FLAKES_TEMPLATE = """# GENERATED by HomeFree admin panel - do not edit by hand.
# Regenerated from homefree-config.json `developers.flakes`.
{ inputs }:
[
  (inputs.homefree-navidrome.nixosModules.default)
]
"""

    # JSON configuration template - this is written to homefree-config.json
    HOMEFREE_JSON_TEMPLATE = """{
  "system": {
    "domain": "@@domain@@",
    "hostName": "@@hostname@@",
    "timeZone": "@@timezone@@",
    "defaultLocale": "@@locale@@",
    "countryCode": "@@country_code@@",
    "elevation": @@elevation@@,
    "latitude": @@latitude@@,
    "longitude": @@longitude@@,
    "unitSystem": "@@unit_system@@",
    "currency": @@currency_json@@,
    "language": @@language_json@@,
    "keyMap": "@@vconsole@@",
    "adminUsername": "@@username@@",
    "adminDescription": "@@fullname@@",
    "adminEmail": "@@email@@",
    "hashedPassword": "@@hashed_password@@",
    "localDomain": "lan",
    "additionalDomains": [],
    "authorizedKeys": [],
    "ssh-key-only": false,
    "wheel-passwordless": false,
    "bootMirror": @@system_boot_mirror@@
  },
  "network": {
    "wan-interface": "@@wan_interface@@",
    "lan-interface": "@@lan_interface@@",
    "router-enable": @@router_enable@@,
    "lan-address": "@@lan_address@@",
    "lan-subnet": "@@lan_subnet@@",
    "dhcp-range-start": "@@dhcp_range_start@@",
    "dhcp-range-end": "@@dhcp_range_end@@",
    "enable-unbound-adblock": false,
    "wan-bitrate-mbps-down": null,
    "wan-bitrate-mbps-up": null,
    "static-ips": []
  },
  "dns": {
    "overrides": [],
    "dynamic-dns": {
      "interval": "10m",
      "usev4": "webv4, webv4=ipinfo.io/ip",
      "usev6": "webv6, webv6=v6.ipinfo.io/ip",
      "zones": []
    },
    "cert-management": null
  },
  "mounts": [],
  "storage": {
    "pools": [],
    "shares": []
  },
  "system-disk-encryption": {
    "enable": @@system_disk_encryption_enable@@
  },
  "snapshots": {
    "system": { "enable": false }
  },
  "sso": {
    "allowUserRegistration": false,
    "per-service": {}
  },
  "services": {},
  "service-config": [],
  "proxied-domains": [],
  "backups": {
    "enable": false,
    "to-path": "",
    "extra-from-paths": [],
    "backblaze-enable": false,
    "backblaze-bucket": ""
  },
  "developers": {
    "flakes": [
      {
        "id": "navidrome",
        "name": "Navidrome",
        "type": "remote",
        "url": "git+https://git.homefree.host/homefree/homefree-navidrome.git",
        "inputName": "homefree-navidrome",
        "moduleAttr": "default",
        "enabled": true,
        "addedAt": "2026-05-18T00:00:00Z"
      }
    ],
    "homefree-base": {
      "enabled": @@base_override_enabled@@,
      "type": "local",
      "url": "@@base_override_url@@"
    }
  }
}
"""

    CONFIGURATION_TEMPLATE = """# Local system configuration overrides for HomeFree
# Most system configuration is managed by HomeFree. The per-instance
# settings live in homefree-config.json and are mapped into homefree.*
# by the shared homefree-config-loader module (wired in flake.nix) —
# there is no generated homefree-configuration.nix anymore.
# This file is for system-specific settings only.
#
# To rebuild: sudo nixos-rebuild switch --flake /etc/nixos#@@hostname@@
# See: https://git.homefree.host/homefree/homefree

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    # disko owns the filesystem / LUKS / swap layout.
    ./disko.nix@@secureboot_import@@@@dev_import@@
  ];

@@bootloader@@

  # NixOS Release Version
  system.stateVersion = "@@nixosversion@@";
}
"""

    # Generated only when the user opts into Secure Boot. Replaces
    # systemd-boot with lanzaboote and adds a first-boot service that
    # enrolls Secure Boot keys when the firmware is in Setup Mode.
    SECUREBOOT_MODULE_TEMPLATE = """# Generated by the HomeFree installer - Secure Boot (lanzaboote).
#
# Requires the user to put firmware into Setup Mode once (a BIOS step).
# The first-boot service below enrolls sbctl keys when Setup Mode is
# detected. lanzaboote-signed images boot fine with Secure Boot OFF, so
# the machine still boots before enrollment.
#
# The `boot.lanzaboote` options come from lanzaboote.nixosModules.lanzaboote,
# which the generated flake.nix adds to the module list.

{ config, lib, pkgs, ... }:

{
  # lanzaboote replaces systemd-boot.
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/var/lib/sbctl";
  };

  environment.systemPackages = with pkgs; [ sbctl ];

  # First-boot oneshot: enroll Secure Boot keys if firmware is in Setup
  # Mode. Safe to no-op when it is not.
  systemd.services.homefree-secureboot-enroll = {
    description = "Enroll Secure Boot keys (lanzaboote)";
    wantedBy = [ "multi-user.target" ];
    after = [ "multi-user.target" ];
    unitConfig.ConditionPathExists = "!/var/lib/homefree/secureboot-enrolled";
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    path = with pkgs; [ sbctl systemd coreutils ];
    script = ''
      set -eu
      mkdir -p /var/lib/homefree
      if sbctl status 2>/dev/null | grep -qi "setup mode.*\\benabled\\b"; then
        sbctl create-keys || true
        sbctl enroll-keys --microsoft
        sbctl sign-all || true
        echo "enrolled" > /var/lib/homefree/secureboot-status
      else
        echo "Firmware not in Setup Mode; skipping key enrollment."
        echo "setup-mode-unavailable" > /var/lib/homefree/secureboot-status
      fi
      touch /var/lib/homefree/secureboot-enrolled
    '';
  };
}
"""

    DEVELOPMENT_OVERRIDES_TEMPLATE = """# Development mode overrides
# This file is automatically generated when development mode is enabled
# It configures the system to use a local homefree codebase for development

{ pkgs, ... }:

{
  # Mark development mode as enabled
  homefree.development = true;

  # Mount the shared folder from QEMU virtiofs (much faster than 9p)
  fileSystems."/mnt/homefree-virtiofs" = {
    device = "mount_homefree_source";
    fsType = "virtiofs";
    options = [ "rw" "nofail" ];
  };

  # Use bindfs to remap ownership so all files appear owned by the VM user
  # This allows full read/write access including in-place edits
  # Files created in VM will preserve the host's original ownership
  fileSystems."/home/@@username@@/homefree" = {
    device = "/mnt/homefree-virtiofs";
    fsType = "fuse.bindfs";
    options = [
      "force-user=@@username@@"
      "force-group=users"
      "chown-ignore"
      "chgrp-ignore"
    ];
  };

  environment.systemPackages = with pkgs; [
    bindfs
    claude-code
  ];

  # Note: The flake.nix already configures homefree-local input
  # This file is available for additional development-specific overrides
  #
  # The virtfs mount uses security_model=none which passes through host
  # filesystem permissions. The host directory must have group write
  # permissions (chmod -R g+w) for the VM user to be able to create and
  # edit files. This is suitable for development environments.
}
"""

    @staticmethod
    def initialize():
        """Initialize the installation service"""
        logger.info("Installation service initialized")

    @staticmethod
    def start() -> bool:
        """Start the installation process in a background thread"""
        if InstallationService._running:
            logger.warning("Installation already in progress")
            return False

        InstallationService._running = True
        InstallationService._status = {
            'step': 'Starting installation...',
            'progress': 0.0,
            'message': 'Preparing to install HomeFree',
            'completed': False,
            'error': None,
        }
        # Clear per-install state from any earlier attempt.
        InstallationService._recovery_passphrase = None
        InstallationService._disko_builder = None

        # Start installation in background thread
        InstallationService._install_thread = threading.Thread(
            target=InstallationService._run_installation,
            daemon=True
        )
        InstallationService._install_thread.start()

        return True

    @staticmethod
    def get_status() -> Dict[str, Any]:
        """Get current installation status.

        Includes the LUKS recovery passphrase once it has been
        generated, so the completion screen can show it to the admin.
        """
        status = InstallationService._status.copy()
        status['recovery_passphrase'] = InstallationService._recovery_passphrase
        return status

    @staticmethod
    def _update_status(step: str, progress: float, message: str):
        """Update installation status"""
        InstallationService._status.update({
            'step': step,
            'progress': progress,
            'message': message,
        })
        logger.info(f"[{progress:.0f}%] {step}: {message}")

    @staticmethod
    def _set_error(error: str):
        """Set installation error"""
        InstallationService._status['error'] = error
        InstallationService._status['completed'] = False
        InstallationService._running = False
        logger.error(f"Installation error: {error}")

    @staticmethod
    def _set_completed():
        """Mark installation as completed"""
        InstallationService._status['completed'] = True
        InstallationService._status['progress'] = 100.0
        InstallationService._running = False
        logger.info("Installation completed successfully")

    @staticmethod
    def _run_installation():
        """Run the installation process"""
        try:
            root_mount_point = "/mnt"

            # Step 1: Partition and format disks
            InstallationService._update_status(
                "Partitioning disks",
                5.0,
                "Creating partitions and filesystems"
            )
            InstallationService._partition_disks(root_mount_point)

            # Step 2: Generate hardware configuration
            InstallationService._update_status(
                "Generating hardware configuration",
                15.0,
                "Detecting hardware and generating configuration"
            )
            InstallationService._generate_hardware_config(root_mount_point)

            # Step 3: Generate NixOS configuration
            InstallationService._update_status(
                "Generating HomeFree configuration",
                25.0,
                "Creating flake.nix and configuration files"
            )
            InstallationService._generate_configs(root_mount_point)

            # Step 4: Initialize git repository
            InstallationService._update_status(
                "Initializing git repository",
                30.0,
                "Setting up git for flake management"
            )
            InstallationService._init_git(root_mount_point)

            # Step 4.5: Setup development mode (before nixos-install)
            config = ConfigService.get_config()
            is_dev_mode = config.get('development_mode', False)
            if is_dev_mode:
                InstallationService._update_status(
                    "Setting up development mode",
                    32.0,
                    "Creating symlinks for shared folder access"
                )
                InstallationService._setup_dev_mode(root_mount_point)

            # Step 5: Run nixos-install
            InstallationService._update_status(
                "Installing HomeFree",
                35.0,
                "Building and installing packages...  (this may take 15-30 minutes)"
            )
            InstallationService._nixos_install(root_mount_point)

            # Step 6: Post-install configuration
            InstallationService._update_status(
                "Finishing installation",
                95.0,
                "Finalizing system configuration"
            )
            InstallationService._post_install(root_mount_point)

            # Complete
            InstallationService._update_status(
                "Installation complete",
                100.0,
                "HomeFree has been successfully installed!"
            )
            InstallationService._set_completed()

        except Exception as e:
            logger.exception("Installation failed")
            InstallationService._set_error(str(e))

    @staticmethod
    def _get_partitioning() -> Dict[str, Any]:
        """Read and normalize the partitioning config from the UI.

        Accepts both the new multi-disk shape ({disks: [...], raid, ...})
        and the legacy single-disk shape ({disk: "...", ...}) so an older
        frontend payload still installs.
        """
        config = ConfigService.get_config()
        partitioning = config.get('partitioning') or {}

        disks = partitioning.get('disks')
        if not disks:
            # Legacy single-disk payload.
            single = partitioning.get('disk')
            disks = [single] if single else []
        # Drop empties / dedupe while preserving order.
        seen = set()
        disks = [d for d in disks if d and not (d in seen or seen.add(d))]
        if not disks:
            raise Exception("No disk selected for installation")

        raid = partitioning.get('raid', 'none')
        if raid not in ('none', 'raid0', 'raid1'):
            raid = 'none'
        if raid != 'none' and len(disks) < 2:
            raise Exception(f"{raid} requires at least 2 disks")
        if raid == 'none' and len(disks) > 1:
            # Multiple disks selected without a RAID level - refuse
            # rather than silently using only the first.
            raise Exception(
                "Multiple disks selected but no RAID level chosen"
            )

        return {
            'disks': disks,
            'raid': raid,
            'use_encryption': partitioning.get('use_encryption', True),
            'use_swap': partitioning.get('use_swap', True),
            'use_lanzaboote': partitioning.get('use_lanzaboote', False),
            # Optional BYO passphrase from the installer's advanced panel.
            # Empty / missing => auto-generate (current default behavior).
            # Validated below in _generate_luks_secrets before use.
            'user_passphrase': partitioning.get('user_passphrase') or '',
        }

    @staticmethod
    def _generate_luks_secrets(user_passphrase: str = "") -> str:
        """Create the install-time LUKS keyfile and decide the recovery
        passphrase.

        disko reads `settings.keyFile` *literally on the live installer*
        at luksFormat time, so the keyfile must exist at LUKS_KEYFILE on
        the running ISO before disko runs. The same file is copied into
        the target's /etc/nixos after disko mounts it (see
        _copy_secrets_to_target) so the installed initrd can read it
        until the first-boot TPM2 service shreds it.

        Recovery passphrase: if `user_passphrase` is non-empty and ≥ 20
        chars, use it verbatim (BYO from the installer's Advanced panel).
        Otherwise auto-generate a fresh 6-base36-group value. The chosen
        value is added as keyslot 2 on every system LUKS partition AND
        persisted to /etc/nixos/secrets/recovery-passphrase.txt as the
        master key for any future encrypted data pool.

        Returns the recovery passphrase for the UI completion screen.
        """
        # Write the keyfile at its literal path on the LIVE system.
        live_secrets_dir = Path(LUKS_KEYFILE).parent
        run_privileged(["mkdir", "-p", str(live_secrets_dir)], check=True)

        # 512-bit random keyfile, base64 text. NO trailing newline:
        # disko's `passwordFile` is read with *passphrase* semantics
        # (newline-stripped) at luksFormat time, while
        # `cryptsetup luksAddKey --key-file` reads it as a *keyfile*
        # (raw bytes to EOF, newline included). A trailing '\n' would
        # therefore make the two see different keys and luksAddKey would
        # fail to authorize (cryptsetup exit 2). With no newline both
        # paths see identical bytes.
        keyfile_content = base64.b64encode(secrets.token_bytes(64)).decode()
        write_file_privileged(LUKS_KEYFILE, keyfile_content)
        run_privileged(["chmod", "600", LUKS_KEYFILE], check=True)

        user_passphrase = (user_passphrase or "").rstrip("\n")
        if user_passphrase:
            if len(user_passphrase) < 20:
                # Defensive: the frontend already enforces this, but a
                # too-short BYO value here would still install — and then
                # silently weaken the encryption. Fail loudly.
                raise Exception(
                    "Recovery passphrase too short — need at least 20 "
                    "characters (got " + str(len(user_passphrase)) + ").")
            recovery_passphrase = user_passphrase
            logger.info("Using admin-supplied recovery passphrase (length=%d)",
                        len(recovery_passphrase))
        else:
            # Human recovery passphrase: 6 base36 groups, easy to transcribe.
            alphabet = string.ascii_lowercase + string.digits
            groups = ["".join(secrets.choice(alphabet) for _ in range(5))
                      for _ in range(6)]
            recovery_passphrase = "-".join(groups)
            logger.info("Generated LUKS keyfile and recovery passphrase")
        return recovery_passphrase

    @staticmethod
    def _copy_secrets_to_target(root_mount_point: str, recovery_passphrase: str):
        """Copy the LUKS keyfile into the target system and stash the
        recovery passphrase, both under /mnt/etc/nixos/secrets.

        Runs after disko has mounted /mnt. The installed initrd reads
        the keyfile at LUKS_KEYFILE until the first-boot TPM2-enroll
        service enrolls a TPM slot and shreds it.
        """
        target_secrets = Path(root_mount_point) / "etc/nixos/secrets"
        mkdir_privileged(str(target_secrets))

        target_keyfile = f"{root_mount_point}{LUKS_KEYFILE}"
        run_privileged(["cp", LUKS_KEYFILE, target_keyfile], check=True)
        run_privileged(["chmod", "600", target_keyfile], check=True)

        # Write the recovery passphrase WITHOUT a trailing newline. The same
        # file is later read by storage_pool.py (`_materialize_master_passphrase`)
        # and the systemd-cryptsetup keyfile path; both must see the EXACT
        # bytes cryptsetup binds to the LUKS slot (`_add_recovery_keyslots`
        # below adds the slot via stdin without `--key-file=-`, i.e. passphrase
        # semantics — newline-stripped). A trailing newline would split:
        # the slot would be bound to "X" but the file-read would see "X\n",
        # and any unlock via the file would fail. Files created before this
        # fix have a trailing newline; runtime readers `rstrip(b"\n")`.
        recovery_path = str(target_secrets / "recovery-passphrase.txt")
        write_file_privileged(recovery_path, recovery_passphrase)
        run_privileged(["chmod", "600", recovery_path], check=True)
        logger.info("Copied LUKS secrets into target /etc/nixos/secrets")

    @staticmethod
    def _release_target_disks(root_mount_point: str):
        """Free up disks/devices left active by a previous install run.

        disko's `destroy` step fails if a target disk still has a mounted
        partition, an open LUKS mapper, or active swap. After a failed or
        repeated install, those linger. Every step here is best-effort:
        a non-zero exit just means there was nothing to release.

        Each cleanup runs as a single `bash -c` script invoked through
        the pkexec wrapper. `umount`/`mount` is a privileged command so
        needs_privilege() escalates the whole shell string.
        """
        # umount is in PRIVILEGED_COMMANDS, so leading the script with it
        # makes needs_privilege() escalate the entire shell command.
        cleanup_script = (
            # Unmount anything under the target mount point, deepest first.
            f"umount -R {root_mount_point} 2>/dev/null || true; "
            f"mount | awk '{{print $3}}' | grep '^{root_mount_point}' "
            f"| sort -r | xargs -r umount -l 2>/dev/null || true; "
            # Disable swap that lives on the disks about to be wiped.
            "swapoff -a 2>/dev/null || true; "
            # Close LUKS mappers the installer may have opened.
            "for m in /dev/mapper/crypt*; do "
            "[ -e \"$m\" ] && cryptsetup close \"$(basename \"$m\")\" "
            "2>/dev/null || true; done"
        )
        run_privileged(cleanup_script, shell=True, check=False)
        logger.info("Released stale mounts / swap / LUKS mappers")

    @staticmethod
    def _partition_disks(root_mount_point: str):
        """Partition, encrypt, format and mount the target disks via disko.

        Generates /mnt/etc/nixos/disko.nix from the UI selection, creates
        the LUKS keyfile when encryption is on, then runs disko in
        destroy,format,mount mode against that file.
        """
        part = InstallationService._get_partitioning()
        disks = part['disks']
        raid = part['raid']
        use_encryption = part['use_encryption']
        use_swap = part['use_swap']

        logger.info(
            f"Disko partitioning: disks={disks} raid={raid} "
            f"encryption={use_encryption} swap={use_swap}"
        )

        # The keyfile must exist at LUKS_KEYFILE on the LIVE installer
        # before disko runs (disko reads settings.keyFile literally).
        recovery_passphrase = None
        if use_encryption:
            recovery_passphrase = InstallationService._generate_luks_secrets(
                user_passphrase=part.get('user_passphrase') or '')
        InstallationService._recovery_passphrase = recovery_passphrase

        # Size swap to RAM (capped) so hibernation works on single-disk;
        # multi-disk installs disable hibernation anyway.
        mem_total = psutil.virtual_memory().total
        swap_size_mb = min(int(mem_total / (1024 * 1024)), 32768)

        builder = DiskoConfigBuilder(
            disks=disks,
            raid=raid,
            use_encryption=use_encryption,
            use_swap=use_swap,
            swap_size_mb=swap_size_mb,
        )
        disko_nix = builder.build()
        InstallationService._disko_builder = builder

        # disko needs its config file before /mnt exists, so write it to
        # a live path. It is copied into the target's /etc/nixos after
        # disko mounts /mnt (see _generate_configs / below).
        live_disko_path = "/tmp/homefree-disko.nix"
        with open(live_disko_path, "w") as f:
            f.write(disko_nix)
        logger.info(f"Wrote disko config to {live_disko_path}")

        # Release stale state from a previous install attempt: an active
        # LUKS mapper, mounted target, or enabled swap on the disks would
        # make disko's `destroy` step fail with the disk busy. Each step
        # is best-effort - it is normal for there to be nothing to clean.
        InstallationService._release_target_disks(root_mount_point)

        # Run disko: destroy,format,mount against the standalone file.
        # --yes-wipe-all-disks skips the interactive confirmation.
        try:
            process = popen_privileged(
                [
                    "disko",
                    "--mode", "destroy,format,mount",
                    "--root-mountpoint", root_mount_point,
                    "--yes-wipe-all-disks",
                    live_disko_path,
                ],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                universal_newlines=True,
            )
            disko_output = []
            for line in process.stdout:
                disko_output.append(line.rstrip())
                logger.info(f"disko: {line.rstrip()}")
            process.wait()
            if process.returncode != 0:
                # Surface the tail of disko's own output in the error so
                # the failure cause is visible in the UI, not just the
                # backend journal.
                tail = "\n".join(disko_output[-15:]) or "(no output)"
                raise Exception(
                    f"disko failed with exit code {process.returncode}.\n"
                    f"Last output:\n{tail}"
                )
        except FileNotFoundError:
            raise Exception(
                "disko command not found - the installer ISO is missing "
                "the disko package"
            )

        # /mnt is now mounted. Write disko.nix into the target config
        # dir so the installed system imports the identical layout.
        nixos_dir = Path(root_mount_point) / "etc/nixos"
        mkdir_privileged(str(nixos_dir))
        write_file_privileged(str(nixos_dir / "disko.nix"), disko_nix)

        # Copy the LUKS secrets into the target and add the recovery
        # passphrase as an extra keyslot on each container so it
        # survives a TPM clear / disk move.
        if use_encryption:
            InstallationService._copy_secrets_to_target(
                root_mount_point, recovery_passphrase
            )
            InstallationService._add_recovery_keyslots(
                root_mount_point, builder, recovery_passphrase
            )

        logger.info("disko partitioning complete")

    @staticmethod
    def _luks_partition_paths(builder: "DiskoConfigBuilder") -> list:
        """Resolve the underlying LUKS *partition* devices (not mappers).

        systemd-cryptenroll and cryptsetup operate on the LUKS partition
        (e.g. /dev/sda2), not the opened mapper. disko labels each LUKS
        partition; we resolve via the by-partlabel symlink.
        """
        paths = []
        # Root LUKS partitions: disko names the partition `root` and
        # labels it with the disk attr prefix.
        for i in range(len(builder.disks)):
            paths.append(f"/dev/disk/by-partlabel/disk-d{i + 1}-root")
        if builder.use_swap:
            for i in range(len(builder.disks)):
                paths.append(f"/dev/disk/by-partlabel/disk-d{i + 1}-swap")
        return paths

    @staticmethod
    def _add_recovery_keyslots(
        root_mount_point: str,
        builder: "DiskoConfigBuilder",
        recovery_passphrase: str,
    ):
        """Add the recovery passphrase as a second keyslot on each LUKS
        container, authorized by the install-time keyfile."""
        keyfile = f"{root_mount_point}{LUKS_KEYFILE}"
        for part in InstallationService._luks_partition_paths(builder):
            try:
                # No trailing "-": with `-` cryptsetup reads the new key
                # as a *keyfile* (raw bytes to EOF), which produces a
                # slot that an interactively-typed boot passphrase cannot
                # unlock. Omitting it makes cryptsetup read the new key
                # from stdin with *passphrase* semantics - one line, the
                # trailing newline stripped - exactly matching what
                # systemd-cryptsetup receives at the boot prompt.
                # `-q` suppresses confirmation prompts for the
                # non-interactive run. `--key-file` authorizes via the
                # existing install-time keyfile.
                proc = popen_privileged(
                    [
                        "cryptsetup", "luksAddKey", "-q",
                        "--key-file", keyfile,
                        part,
                    ],
                    stdin=subprocess.PIPE,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                )
                # Trailing newline terminates the passphrase read and is
                # stripped - matches the user pressing Enter at boot.
                out, _ = proc.communicate(input=recovery_passphrase + "\n")
                if proc.returncode != 0:
                    # A RAID member without the recovery passphrase slot
                    # produces an unbootable system - fail hard, do not
                    # let the install "succeed" into a broken state.
                    raise Exception(
                        f"cryptsetup luksAddKey failed on {part} "
                        f"(exit {proc.returncode}): {out}"
                    )
                logger.info(f"Added recovery keyslot on {part}")
            except Exception as e:
                # Abort the install: a LUKS container the user cannot
                # unlock with the recovery passphrase means an
                # unbootable system. Better to fail the install loudly.
                logger.error(
                    f"Could not add recovery keyslot on {part}: {e}"
                )
                raise Exception(
                    f"Failed to add recovery passphrase to {part}; "
                    f"aborting install to avoid an unbootable system: {e}"
                ) from e

    @staticmethod
    def _generate_hardware_config(root_mount_point: str):
        """Generate hardware-configuration.nix (hardware bits only).

        --no-filesystems omits the fileSystems/swapDevices stanza:
        disko.nix is the single source of truth for the disk layout,
        so letting nixos-generate-config also emit fileSystems would
        produce a conflicting definition.
        """
        try:
            run_privileged(
                ["nixos-generate-config", "--no-filesystems",
                 "--root", root_mount_point],
                check=True,
                capture_output=True
            )
        except subprocess.CalledProcessError as e:
            raise Exception(f"Failed to generate hardware config: {e.stderr.decode()}")

    @staticmethod
    def _generate_configs(root_mount_point: str):
        """Generate flake.nix, homefree-config.json, and configuration.nix"""
        config = ConfigService.get_config()
        nixos_dir = Path(root_mount_point) / "etc/nixos"
        mkdir_privileged(str(nixos_dir))

        # Get NixOS version
        try:
            version = subprocess.check_output(["nixos-version"]).decode().strip()
            version = '.'.join(version.split('.')[:2])[:5]
        except:
            version = "24.05"

        # Detect firmware type
        fw_type = "efi" if Path("/sys/firmware/efi").exists() else "bios"

        # Partitioning / encryption / Secure Boot selections.
        part = InstallationService._get_partitioning()
        use_encryption = part['use_encryption']
        use_lanzaboote = part['use_lanzaboote'] and fw_type == "efi"
        first_disk = part['disks'][0]

        # Generate bootloader config. When lanzaboote (Secure Boot) is
        # opted in, secureboot.nix owns the bootloader and sets
        # systemd-boot off via mkForce, so we emit nothing here.
        if use_lanzaboote:
            bootloader = """  # Bootloader: managed by secureboot.nix (lanzaboote)
"""
        elif fw_type == "efi":
            # The boot-mirror rsync hook (for raid='raid1' installs that
            # have a second ESP at /boot2) is no longer emitted here.
            # It lives in shared code under modules/boot-mirror.nix and
            # is gated on homefree.system.bootMirror, set from the JSON
            # field of the same name (see HOMEFREE_JSON_TEMPLATE below
            # and modules/homefree-config-loader.nix).
            bootloader = """  # Bootloader (UEFI)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
"""
        else:
            bootloader = f"""  # Bootloader (BIOS)
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "{first_disk}";
  boot.loader.grub.useOSProber = true;
"""

        # Get network interfaces
        wan_interface = NetworkService.get_wan_interface() or ''
        lan_interface = NetworkService.get_lan_interface() or ''

        # Check if development mode is enabled
        is_dev_mode = config.get('development_mode', False)
        username = config.get('username', 'admin')

        # Generate router config only if both interfaces are configured
        if wan_interface and lan_interface:
            router_base = f"""      # Network interfaces
      wan-interface = "{wan_interface}";
      lan-interface = "{lan_interface}";

      # Enable router functionality
      router.enable = true;
"""
            # Add development mode network configuration if enabled
            if is_dev_mode:
                # In router mode with dev mode, use 10.1.2.x for LAN subnet (bridge network)
                router_config = router_base + """
      # Development mode network configuration (QEMU bridge networking for router mode)
      lan-address = "10.1.2.1";
      lan-subnet = "10.1.2.0/24";
      dhcp-range-start = "10.1.2.100";
      dhcp-range-end = "10.1.2.200";
"""
            else:
                router_config = router_base
        else:
            # Router mode disabled, but still include dev mode network config if enabled
            if is_dev_mode:
                # In non-router mode with dev mode, use 10.0.2.x (QEMU user networking)
                router_config = """      # Router mode disabled - insufficient network interfaces
      router.enable = false;

      # Development mode network configuration (QEMU user networking)
      lan-address = "10.0.2.15";
      lan-subnet = "10.0.2.0/24";
      dhcp-range-start = "10.0.2.100";
      dhcp-range-end = "10.0.2.200";
"""
            else:
                router_config = """      # Router mode disabled - insufficient network interfaces
      router.enable = false;
"""

        # Generate hashed password using mkpasswd
        password = config.get('password', '')
        if not password:
            raise Exception(
                "No password configured for the admin user; cannot generate "
                "hashedPassword for NixOS configuration"
            )

        # Pass the password via stdin to keep it out of /proc/<pid>/cmdline
        # and to avoid a leading '-' being parsed as a flag.
        try:
            result = subprocess.run(
                ['mkpasswd', '-m', 'sha-512', '--stdin'],
                input=password,
                capture_output=True,
                text=True,
                check=True
            )
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to hash password: {e.stderr}")
            raise Exception(f"Failed to hash admin password with mkpasswd: {e.stderr.strip() or e}") from e

        hashed_password = result.stdout.strip()
        if not hashed_password:
            raise Exception("mkpasswd produced an empty hash for the admin password")
        logger.info("Generated hashed password for user")

        # Development mode template variables.
        #
        # Dev mode is just the alternate-HomeFree-base feature pre-enabled
        # with a local repo: the managed `homefree-base-override` region is
        # populated with a `homefree-alt` input pointing at the local
        # checkout, and the `homefree-base-binding` region selects it. The
        # admin panel's Developers section drives the same two regions
        # post-install. (A production install leaves the override region
        # empty and the binding on `homefree-base`.)
        if is_dev_mode:
            # Use /home/nixos/homefree during install (where virtfs is mounted)
            # After install, _post_install will update this to /home/<username>/homefree
            base_override_region = """
    homefree-alt.url = "git+file:///home/nixos/homefree";"""
            base_binding_target = "homefree-alt"
            # Keep homefree-config.json's developers.homefree-base in sync
            # with the flake so the admin UI shows the alternate-base panel
            # correctly. _post_install rewrites the /home/nixos path here too.
            base_override_enabled = "true"
            base_override_url = "git+file:///home/nixos/homefree"
            dev_import = "\n    ./development-overrides.nix"
        else:
            base_override_region = ""
            base_binding_target = "homefree-base"
            base_override_enabled = "false"
            base_override_url = ""
            dev_import = ""

        # disko / lanzaboote / encryption flake + import wiring.
        # disko is always an input now (it owns the disk layout).
        if use_lanzaboote:
            lanzaboote_input = (
                f'\n    lanzaboote.url = "{LANZABOOTE_FLAKE_REF}";'
                '\n    lanzaboote.inputs.nixpkgs.follows = "nixpkgs";'
            )
            lanzaboote_output_arg = ", lanzaboote"
            lanzaboote_module = "\n          lanzaboote.nixosModules.lanzaboote"
            secureboot_import = "\n    ./secureboot.nix"
        else:
            lanzaboote_input = ""
            lanzaboote_output_arg = ""
            lanzaboote_module = ""
            secureboot_import = ""

        # System-disk LUKS support is now a shared module
        # (services/system-disk-encryption/default.nix), gated on
        # homefree.system-disk-encryption.enable. The installer flips
        # the JSON key below; configuration.nix no longer needs a
        # per-instance ./homefree-encryption.nix import. Scoped to
        # SYSTEM disks only — data pools are encrypted per-pool via
        # homefree.storage.
        system_disk_encryption_enable = "true" if use_encryption else "false"

        # Boot mirror toggle. Flipped on when raid='raid1' is selected —
        # disko_builder provisions a second ESP on disk 2 at /boot2 in
        # that case, and modules/boot-mirror.nix applies the rsync hook
        # that keeps it in sync with /boot. Single-disk and raid0 leave
        # it false (no /boot2 to mirror to).
        system_boot_mirror = "true" if part['raid'] == 'raid1' else "false"

        # Determine network configuration values for JSON
        if wan_interface and lan_interface:
            router_enable = "true"
            if is_dev_mode:
                # In router mode with dev mode, use 10.1.2.x for LAN subnet (bridge network)
                lan_address = "10.1.2.1"
                lan_subnet = "10.1.2.0/24"
                dhcp_range_start = "10.1.2.100"
                dhcp_range_end = "10.1.2.200"
            else:
                # Default router mode values
                lan_address = "10.0.0.1"
                lan_subnet = "10.0.0.0/24"
                dhcp_range_start = "10.0.0.100"
                dhcp_range_end = "10.0.0.200"
        else:
            # Router mode disabled
            router_enable = "false"
            if is_dev_mode:
                # In non-router mode with dev mode, use 10.0.2.x (QEMU user networking)
                lan_address = "10.0.2.15"
                lan_subnet = "10.0.2.0/24"
                dhcp_range_start = "10.0.2.100"
                dhcp_range_end = "10.0.2.200"
            else:
                # Fallback values when router is disabled
                lan_address = "10.0.0.1"
                lan_subnet = "10.0.0.0/24"
                dhcp_range_start = "10.0.0.100"
                dhcp_range_end = "10.0.0.200"

        # Template variables. Localization fields use helpers so an
        # unset (None / "") value renders as JSON `null` rather than
        # the string "None" — homefree-config.json must be valid JSON.
        def _json_or_null(v):
            return "null" if v in (None, "") else str(v)
        def _json_or_quoted_str(v):
            return "null" if v in (None, "") else '"%s"' % str(v).replace('"', '\\"')

        variables = {
            'hostname': config.get('hostname', 'homefree'),
            'domain': config.get('domain', 'homefree.host'),
            'timezone': config.get('timezone', 'America/Los_Angeles'),
            'locale': config.get('locale', 'en_US.UTF-8'),
            'country_code': config.get('country_code', 'US'),
            'elevation': _json_or_null(config.get('elevation')),
            'latitude': _json_or_null(config.get('latitude')),
            'longitude': _json_or_null(config.get('longitude')),
            'unit_system': config.get('unit_system', 'metric'),
            'currency_json': _json_or_quoted_str(config.get('currency')),
            'language_json': _json_or_quoted_str(config.get('language')),
            'vconsole': config.get('vconsole', 'us'),
            'username': username,
            'fullname': config.get('fullname', 'HomeFree Admin'),
            'email': config.get('email', ''),
            'wan_interface': wan_interface,
            'lan_interface': lan_interface,
            'router_enable': router_enable,
            'lan_address': lan_address,
            'lan_subnet': lan_subnet,
            'dhcp_range_start': dhcp_range_start,
            'dhcp_range_end': dhcp_range_end,
            'nixosversion': version,
            'bootloader': bootloader,
            'router_config': router_config,
            'hashed_password': hashed_password,
            'base_override_region': base_override_region,
            'base_binding_target': base_binding_target,
            'base_override_enabled': base_override_enabled,
            'base_override_url': base_override_url,
            'dev_import': dev_import,
            'lanzaboote_input': lanzaboote_input,
            'lanzaboote_output_arg': lanzaboote_output_arg,
            'lanzaboote_module': lanzaboote_module,
            'secureboot_import': secureboot_import,
            'system_disk_encryption_enable': system_disk_encryption_enable,
            'system_boot_mirror': system_boot_mirror,
        }

        # Generate homefree-config.json first
        json_content = InstallationService.HOMEFREE_JSON_TEMPLATE
        for key, value in variables.items():
            json_content = json_content.replace(f"@@{key}@@", str(value))

        write_file_privileged(str(nixos_dir / "homefree-config.json"), json_content)
        logger.info("Generated homefree-config.json")

        # Generate flake.nix
        flake_content = InstallationService.FLAKE_TEMPLATE
        for key, value in variables.items():
            flake_content = flake_content.replace(f"@@{key}@@", str(value))

        write_file_privileged(str(nixos_dir / "flake.nix"), flake_content)

        # Generate the initial (empty) custom-flakes.nix. flake.nix imports
        # this; the admin panel's Developers section regenerates it when
        # custom flakes are registered. Written even with no flakes so the
        # build is self-contained and git-tracked from first boot.
        write_file_privileged(
            str(nixos_dir / "custom-flakes.nix"),
            InstallationService.CUSTOM_FLAKES_TEMPLATE,
        )

        # No homefree-configuration.nix is generated anymore. The
        # homefree-config.json → homefree.* mapping lives in the shared
        # repo (modules/homefree-config-loader.nix), wired into the
        # module system by flake.nix via specialArgs. See
        # docs/agent-notes/homefree-configuration-nix-is-generated.md.

        # Generate configuration.nix
        configuration = InstallationService.CONFIGURATION_TEMPLATE
        for key, value in variables.items():
            configuration = configuration.replace(f"@@{key}@@", str(value))

        write_file_privileged(str(nixos_dir / "configuration.nix"), configuration)

        # System-disk LUKS support is provided by the shared module
        # services/system-disk-encryption/default.nix, activated by
        # the `system-disk-encryption.enable` key the JSON template
        # above carries. No per-instance file is generated here.

        # Generate secureboot.nix when the user opted into Secure Boot.
        if use_lanzaboote:
            write_file_privileged(
                str(nixos_dir / "secureboot.nix"),
                InstallationService.SECUREBOOT_MODULE_TEMPLATE,
            )
            logger.info("Generated secureboot.nix")

        # Generate development-overrides.nix if in development mode
        if is_dev_mode:
            dev_overrides = InstallationService.DEVELOPMENT_OVERRIDES_TEMPLATE.replace("@@username@@", username)
            write_file_privileged(str(nixos_dir / "development-overrides.nix"), dev_overrides)
            logger.info("Generated development-overrides.nix for development mode")

        logger.info(f"Generated configuration files in {nixos_dir}")

    @staticmethod
    def _init_git(root_mount_point: str):
        """Initialize git repository for flake"""
        nixos_dir = Path(root_mount_point) / "etc/nixos"

        try:
            # Git operations on /mnt need privilege escalation
            run_privileged(["git", "init", str(nixos_dir)], check=True)

            # Keep the LUKS keyfile / recovery passphrase out of git
            # history - they live on disk only, read at boot time.
            write_file_privileged(
                str(nixos_dir / ".gitignore"),
                "# Disk-encryption secrets - never commit these.\nsecrets/\n",
            )

            run_privileged(["git", "-C", str(nixos_dir), "add", "."], check=True)
            run_privileged(
                ["git", "-C", str(nixos_dir), "config", "user.email", "installer@homefree.local"],
                check=True
            )
            run_privileged(
                ["git", "-C", str(nixos_dir), "config", "user.name", "HomeFree Installer"],
                check=True
            )
            run_privileged(
                ["git", "-C", str(nixos_dir), "commit", "-m", "Initial configuration"],
                check=True
            )
            logger.info("Initialized git repository")
        except subprocess.CalledProcessError as e:
            raise Exception(f"Failed to initialize git: {e}")

    @staticmethod
    def _seed_sbctl_keys(root_mount_point: str):
        """Generate sbctl Secure Boot keys at /mnt/var/lib/sbctl BEFORE the
        lanzaboote bootloader installer runs as part of nixos-install.

        The lanzaboote installer reads the public key at
        `${pkiBundle}/keys/db/db.pem` to compute each stub's input-addressed
        name AND to sign each stub. With no keys present it bails at the very
        first generation:

            Failed to install generation 1:
              Get stub name: No such file or directory (os error 2)

        Generating keys here ENROLLS NOTHING into firmware — that's the
        first-boot `homefree-secureboot-enroll` oneshot's job (which runs
        `sbctl enroll-keys` only when firmware is in Setup Mode). These are
        just the local PKI bundle lanzaboote needs to sign images at
        activation time.

        Idempotent: re-running install after a previous failure sees the
        existing key file and skips. Output paths land directly under the
        target so nixos-install's bootloader step (which chroots into /mnt)
        sees them at the path the lanzaboote NixOS module references by
        default (`${cfg.pkiBundle}/keys/db/db.pem`).
        """
        target_sbctl = f"{root_mount_point}/var/lib/sbctl"
        target_keydir = f"{target_sbctl}/keys"
        target_guid = f"{target_sbctl}/GUID"
        public_key = f"{target_keydir}/db/db.pem"

        # Existence probe through stat — the nixos user can't read under
        # /mnt directly, but the pkexec wrapper has coreutils on PATH.
        # `--` guards against any path that starts with `-`. Return code 0 =
        # the public key file exists, so a previous run already seeded keys
        # for this install and we can skip.
        rc = run_privileged(
            ["stat", "-t", "--", public_key],
            capture_output=True, check=False).returncode
        if rc == 0:
            logger.info(
                "Secure Boot keys already present at %s — skipping create.",
                public_key)
            return

        run_privileged(["mkdir", "-p", target_keydir], check=True)

        # `--export <dir>` overrides sbctl's default Keydir; `--database-path
        # <file>` overrides the GUID file path. `--disable-landlock` avoids
        # the landlock sandbox restricting writes outside /var/lib/sbctl on
        # the live ISO (we're writing into /mnt instead). Pure list args —
        # no shell wrapping, no env-var games, no quoting hazards.
        logger.info("Generating Secure Boot keys at %s", target_keydir)
        try:
            result = run_privileged(
                ["sbctl",
                 "--disable-landlock",
                 "create-keys",
                 "--export", target_keydir,
                 "--database-path", target_guid],
                capture_output=True, text=True, check=True)
            output = (result.stdout or "").strip()
            if output:
                logger.info("sbctl: %s", output)
        except subprocess.CalledProcessError as e:
            err = ((e.stderr or "") + (e.stdout or "")).strip()
            raise Exception(
                "Failed to generate Secure Boot keys for lanzaboote: "
                + (err or str(e))) from e

    @staticmethod
    def _nixos_install(root_mount_point: str):
        """Run nixos-install"""
        import os

        config = ConfigService.get_config()
        hostname = config.get('hostname', 'homefree')

        # When the user opted into Secure Boot, generate the sbctl PKI under
        # the target FIRST. nixos-install's bootloader step is lanzaboote's
        # installer when `boot.lanzaboote.enable = true`; that installer fails
        # with "Get stub name: No such file or directory" unless the keys are
        # in place. Inexpensive to compute at install time and idempotent.
        part = InstallationService._get_partitioning()
        fw_type = "efi" if Path("/sys/firmware/efi").exists() else "bios"
        if part.get('use_lanzaboote') and fw_type == "efi":
            InstallationService._seed_sbctl_keys(root_mount_point)

        try:
            # nixos-install automatically prepends 'nixosConfigurations.' so just pass the hostname
            flake_ref = f"{root_mount_point}/etc/nixos#{hostname}"
            logger.info(f"Installing NixOS with flake reference: {flake_ref}")

            # Log the generated flake.nix content for debugging
            # Note: We can't read the file directly from /mnt as nixos user,
            # but we can use cat via pkexec or just skip this debug step
            try:
                flake_path = Path(root_mount_point) / "etc/nixos/flake.nix"
                # Use privileged read via cat
                result = run_privileged(
                    ["cat", str(flake_path)],
                    capture_output=True,
                    text=True,
                    check=True
                )
                logger.info(f"Flake content:\n{result.stdout}")
            except Exception as e:
                logger.warning(f"Could not read flake.nix: {e}")

            # DEBUG: Test what the flake reference resolves to
            import subprocess as sp
            try:
                test_cmd = [
                    "nix", "--extra-experimental-features", "nix-command flakes",
                    "flake", "show", flake_ref, "--json"
                ]
                test_result = sp.run(test_cmd, capture_output=True, text=True, timeout=30)
                logger.info(f"DEBUG flake show output: {test_result.stdout[:500]}")
                logger.info(f"DEBUG flake show stderr: {test_result.stderr[:500]}")
            except Exception as e:
                logger.warning(f"DEBUG flake show failed: {e}")

            # Build nixos-install command with --show-trace for better error messages
            cmd = [
                "nixos-install",
                "--debug",  # Enable bash set -x for detailed debugging
                "--flake", flake_ref,
                "--no-root-passwd",
                "--root", root_mount_point,
                "--show-trace"  # Add detailed error tracing
            ]

            # Log the exact command being run
            logger.info(f"Running command: {' '.join(cmd)}")
            logger.info(f"Inheriting environment from systemd service (preserves PATH with Nix tools)")

            # Run nixos-install inheriting the systemd service environment
            # This preserves the PATH that includes all necessary Nix commands
            process = popen_privileged(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                universal_newlines=True
            )

            # Stream output and update progress
            progress = 35.0
            output_lines = []
            for line in process.stdout:
                output_lines.append(line)
                line_stripped = line.strip()
                logger.info(f"nixos-install: {line_stripped}")

                # Update progress based on different types of output
                updated = False

                # Evaluating/preparing (early phase)
                if any(keyword in line.lower() for keyword in ["evaluating", "preparing"]):
                    progress = min(progress + 0.1, 50.0)
                    InstallationService._update_status(
                        "Preparing installation",
                        progress,
                        line_stripped[:100]
                    )
                    updated = True

                # Nix operations (copying, downloading, fetching, building) - treat all equally
                elif any(keyword in line.lower() for keyword in ["copying", "downloading", "fetching", "building"]):
                    progress = min(progress + 0.2, 85.0)

                    # Determine the action and extract details
                    if "building" in line.lower():
                        step_name = "Building packages"
                        # Try to extract package name
                        if "'" in line:
                            parts = line.split("'")
                            if len(parts) >= 2:
                                pkg_name = parts[1].split("/")[-1] if "/" in parts[1] else parts[1]
                                message = f"Building {pkg_name}"
                            else:
                                message = line_stripped[:100]
                        else:
                            message = line_stripped[:100]
                    elif "copying" in line.lower():
                        step_name = "Installing HomeFree"
                        message = line_stripped[:100]
                    elif "downloading" in line.lower() or "fetching" in line.lower():
                        step_name = "Downloading packages"
                        message = line_stripped[:100]
                    else:
                        step_name = "Installing HomeFree"
                        message = line_stripped[:100]

                    InstallationService._update_status(
                        step_name,
                        progress,
                        message
                    )
                    updated = True

                # Installing/setting up packages
                elif "installing" in line.lower() or "setting up" in line.lower():
                    progress = min(progress + 0.2, 90.0)
                    InstallationService._update_status(
                        "Installing packages",
                        progress,
                        line_stripped[:100]
                    )
                    updated = True

                # Activating system
                elif "activating" in line.lower() or "systemd" in line.lower():
                    progress = min(progress + 0.3, 92.0)
                    InstallationService._update_status(
                        "Activating system",
                        progress,
                        line_stripped[:100]
                    )
                    updated = True

            process.wait()

            # Log full output if failed for debugging
            if process.returncode != 0:
                logger.error(f"nixos-install failed with exit code {process.returncode}")
                logger.error(f"Full output:\n{''.join(output_lines[-100:])}")  # Last 100 lines
                raise Exception(f"nixos-install failed with code {process.returncode}")

            logger.info("nixos-install completed successfully")

        except Exception as e:
            raise Exception(f"Failed to install HomeFree: {e}")

    @staticmethod
    def _setup_dev_mode(root_mount_point: str):
        """Setup development mode before nixos-install"""
        config = ConfigService.get_config()
        username = config.get('username', 'admin')

        try:
            logger.info("Setting up development mode")

            # Create symlink from /home/<username>/homefree to /home/nixos/homefree
            # This makes the nixos user's mounted folder accessible at the final user's path
            homefree_link = f"/home/{username}/homefree"
            try:
                # Create parent directory if needed (needs sudo for /home)
                run_privileged(["mkdir", "-p", f"/home/{username}"], check=True)
                # Create symlink
                run_privileged(["ln", "-sf", "/home/nixos/homefree", homefree_link], check=True)
                logger.info(f"Created symlink {homefree_link} -> /home/nixos/homefree")

                # Configure git to trust these directories (needed for git+file:// URLs in flake)
                run_privileged(["git", "config", "--global", "--add", "safe.directory", "/home/nixos/homefree"], check=True)
                run_privileged(["git", "config", "--global", "--add", "safe.directory", homefree_link], check=True)
                logger.info("Configured git safe.directory for homefree paths")
            except Exception as e:
                logger.error(f"Failed to create homefree symlink: {e}")
                raise Exception("Cannot proceed with development mode installation")

            # Create the actual directory in /mnt for after reboot
            # This directory will be the mount point for the shared folder
            homefree_dir = f"{root_mount_point}/home/{username}/homefree"
            mkdir_privileged(homefree_dir)

            # Set ownership on the directory (default first user UID/GID)
            uid = "1000"
            gid = "100"
            run_privileged(["chown", f"{uid}:{gid}", homefree_dir], check=True)

            # Note: The filesystem mount is now configured in development-overrides.nix
            # NixOS will handle mounting via fileSystems configuration

            logger.info("Development mode setup complete")

        except Exception as e:
            logger.error(f"Failed to setup development mode: {e}")
            raise

    @staticmethod
    def _post_install(root_mount_point: str):
        """Post-installation tasks"""
        config = ConfigService.get_config()
        username = config.get('username', 'admin')
        password = config.get('password', '')

        # Set password using chpasswd in the installed system
        # This matches the standard NixOS installer behavior
        if not password:
            raise Exception(
                "No password configured for the admin user; cannot run chpasswd "
                "in the installed system"
            )

        logger.info(f"Setting password for user {username} using chpasswd")

        # Format: username:password (chpasswd splits on the first colon, so a
        # colon in the password is preserved). Password has already been
        # validated to contain no newlines.
        passwd_input = f"{username}:{password}\n"

        process = popen_privileged(
            ["nixos-enter", "--root", root_mount_point, "--", "chpasswd"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        stdout, stderr = process.communicate(input=passwd_input)

        if process.returncode != 0:
            logger.error(f"chpasswd failed: {stderr}")
            raise Exception(
                f"Failed to set password for user {username} via chpasswd: "
                f"{stderr.strip() or 'exit code ' + str(process.returncode)}"
            )
        logger.info(f"Successfully set password for user {username} via chpasswd")

        # Stash the plaintext password where Zitadel's first-instance
        # bootstrap can find it. The Zitadel container's preStart reads
        # this file to populate ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD,
        # so the human user created on first boot has the same password
        # as the OS admin user. Future password changes propagate via
        # the PAM bridge (see services/zitadel-pam-bridge.nix).
        zitadel_secrets_dir = f"{root_mount_point}/var/lib/homefree-secrets/zitadel"
        zitadel_password_file = f"{zitadel_secrets_dir}/admin-password"
        try:
            mkdir_privileged(zitadel_secrets_dir)
            run_privileged(["chmod", "700", zitadel_secrets_dir], check=True)
            write_file_privileged(zitadel_password_file, password)
            run_privileged(["chmod", "600", zitadel_password_file], check=True)
            logger.info(f"Stashed admin password for Zitadel bootstrap at {zitadel_password_file}")
        except Exception as e:
            # Non-fatal: if this fails Zitadel just falls back to its
            # initial-password default and the admin needs to set it
            # manually on first login. We don't want a missing secrets
            # dir to block the entire install.
            logger.warning(f"Failed to stash Zitadel admin password (non-fatal): {e}")

        # Update flake.nix for development mode
        if ConfigService.is_development_mode():
            try:
                logger.info("Updating flake.nix for development mode post-install")
                flake_path = f"{root_mount_point}/etc/nixos/flake.nix"

                # Read current flake.nix
                with open(flake_path, 'r') as f:
                    flake_content = f.read()

                # Replace /home/nixos/homefree with /home/<username>/homefree
                # This path will be valid after reboot when fstab mounts the shared folder
                updated_content = flake_content.replace(
                    'git+file:///home/nixos/homefree',
                    f'git+file:///home/{username}/homefree'
                )

                # Write back (using write_file_privileged since /mnt requires root)
                write_file_privileged(flake_path, updated_content)

                logger.info(f"Updated flake.nix to use /home/{username}/homefree")

                # Keep homefree-config.json's developers.homefree-base.url in
                # sync with the flake's homefree-alt input — the admin panel
                # reads the URL from JSON for the alternate-base panel.
                try:
                    json_path = f"{root_mount_point}/etc/nixos/homefree-config.json"
                    with open(json_path, 'r') as f:
                        json_content = f.read()
                    json_content = json_content.replace(
                        'git+file:///home/nixos/homefree',
                        f'git+file:///home/{username}/homefree'
                    )
                    write_file_privileged(json_path, json_content)
                    logger.info("Updated homefree-config.json alternate-base URL")
                except Exception as json_error:
                    logger.warning(
                        f"Failed to update homefree-config.json base URL: {json_error}"
                    )

                # Configure git to trust the homefree directory in the installed system
                # This is needed because the shared folder may have different ownership
                try:
                    run_privileged(
                        ["nixos-enter", "--root", root_mount_point, "--",
                         "git", "config", "--global", "--add", "safe.directory", f"/home/{username}/homefree"],
                        check=True
                    )
                    logger.info(f"Configured git safe.directory for /home/{username}/homefree in installed system")
                except Exception as git_error:
                    logger.warning(f"Failed to configure git safe.directory: {git_error}")
                    logger.info("You may need to run: git config --global --add safe.directory /home/{username}/homefree")

            except Exception as e:
                logger.error(f"Failed to update flake.nix for development mode: {e}")
                logger.warning("Development mode may not work after reboot")

        logger.info(f"Post-install complete for user {username}")
